package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdjuntoId generated by hbm2java
 */
@Embeddable
public class AdjuntoId implements java.io.Serializable {

	private int codigoAdjunto;
	private int codigoSolicitud;
	private int codigoUsuario;

	public AdjuntoId() {
	}

	public AdjuntoId(int codigoAdjunto, int codigoSolicitud, int codigoUsuario) {
		this.codigoAdjunto = codigoAdjunto;
		this.codigoSolicitud = codigoSolicitud;
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigoAdjunto", nullable = false)
	public int getCodigoAdjunto() {
		return this.codigoAdjunto;
	}

	public void setCodigoAdjunto(int codigoAdjunto) {
		this.codigoAdjunto = codigoAdjunto;
	}

	@Column(name = "codigoSolicitud", nullable = false)
	public int getCodigoSolicitud() {
		return this.codigoSolicitud;
	}

	public void setCodigoSolicitud(int codigoSolicitud) {
		this.codigoSolicitud = codigoSolicitud;
	}

	@Column(name = "codigoUsuario", nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdjuntoId))
			return false;
		AdjuntoId castOther = (AdjuntoId) other;

		return (this.getCodigoAdjunto() == castOther.getCodigoAdjunto())
				&& (this.getCodigoSolicitud() == castOther.getCodigoSolicitud())
				&& (this.getCodigoUsuario() == castOther.getCodigoUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoAdjunto();
		result = 37 * result + this.getCodigoSolicitud();
		result = 37 * result + this.getCodigoUsuario();
		return result;
	}

}
