package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CambioAdjuntoId generated by hbm2java
 */
@Embeddable
public class CambioAdjuntoId implements java.io.Serializable {

	private int codigoAdjunto;
	private int codigoCambio;

	public CambioAdjuntoId() {
	}

	public CambioAdjuntoId(int codigoAdjunto, int codigoCambio) {
		this.codigoAdjunto = codigoAdjunto;
		this.codigoCambio = codigoCambio;
	}

	@Column(name = "codigoAdjunto", nullable = false)
	public int getCodigoAdjunto() {
		return this.codigoAdjunto;
	}

	public void setCodigoAdjunto(int codigoAdjunto) {
		this.codigoAdjunto = codigoAdjunto;
	}

	@Column(name = "codigoCambio", nullable = false)
	public int getCodigoCambio() {
		return this.codigoCambio;
	}

	public void setCodigoCambio(int codigoCambio) {
		this.codigoCambio = codigoCambio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CambioAdjuntoId))
			return false;
		CambioAdjuntoId castOther = (CambioAdjuntoId) other;

		return (this.getCodigoAdjunto() == castOther.getCodigoAdjunto())
				&& (this.getCodigoCambio() == castOther.getCodigoCambio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoAdjunto();
		result = 37 * result + this.getCodigoCambio();
		return result;
	}

}
