package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CambioProblemaId generated by hbm2java
 */
@Embeddable
public class CambioProblemaId implements java.io.Serializable {

	private int codigoCambio;
	private int codigoProblema;

	public CambioProblemaId() {
	}

	public CambioProblemaId(int codigoCambio, int codigoProblema) {
		this.codigoCambio = codigoCambio;
		this.codigoProblema = codigoProblema;
	}

	@Column(name = "codigoCambio", nullable = false)
	public int getCodigoCambio() {
		return this.codigoCambio;
	}

	public void setCodigoCambio(int codigoCambio) {
		this.codigoCambio = codigoCambio;
	}

	@Column(name = "codigoProblema", nullable = false)
	public int getCodigoProblema() {
		return this.codigoProblema;
	}

	public void setCodigoProblema(int codigoProblema) {
		this.codigoProblema = codigoProblema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CambioProblemaId))
			return false;
		CambioProblemaId castOther = (CambioProblemaId) other;

		return (this.getCodigoCambio() == castOther.getCodigoCambio())
				&& (this.getCodigoProblema() == castOther.getCodigoProblema());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCambio();
		result = 37 * result + this.getCodigoProblema();
		return result;
	}

}
