package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CambioNotaId generated by hbm2java
 */
@Embeddable
public class CambioNotaId implements java.io.Serializable {

	private int codigoNota;
	private int codigoCambio;

	public CambioNotaId() {
	}

	public CambioNotaId(int codigoNota, int codigoCambio) {
		this.codigoNota = codigoNota;
		this.codigoCambio = codigoCambio;
	}

	@Column(name = "codigoNota", nullable = false)
	public int getCodigoNota() {
		return this.codigoNota;
	}

	public void setCodigoNota(int codigoNota) {
		this.codigoNota = codigoNota;
	}

	@Column(name = "codigoCambio", nullable = false)
	public int getCodigoCambio() {
		return this.codigoCambio;
	}

	public void setCodigoCambio(int codigoCambio) {
		this.codigoCambio = codigoCambio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CambioNotaId))
			return false;
		CambioNotaId castOther = (CambioNotaId) other;

		return (this.getCodigoNota() == castOther.getCodigoNota())
				&& (this.getCodigoCambio() == castOther.getCodigoCambio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoNota();
		result = 37 * result + this.getCodigoCambio();
		return result;
	}

}
