package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CambioMiembro generated by hbm2java
 */
@Entity
@Table(name = "CAMBIO_MIEMBRO", schema = "dbo", catalog = "SISMAV2")
public class CambioMiembro implements java.io.Serializable {

	private CambioMiembroId id;
	private Cambio cambio;
	private MiembroCab miembroCab;
	private String recomendacion;
	private String comentario;
	private String enviadoEn;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;

	public CambioMiembro() {
	}

	public CambioMiembro(CambioMiembroId id, Cambio cambio,
			MiembroCab miembroCab) {
		this.id = id;
		this.cambio = cambio;
		this.miembroCab = miembroCab;
	}

	public CambioMiembro(CambioMiembroId id, Cambio cambio,
			MiembroCab miembroCab, String recomendacion, String comentario,
			String enviadoEn, Integer estado, String usuarioCreacion,
			Date fechaCreacion, String terminalCreacion,
			String usuarioModificacion, Date fechaModificacion,
			String terminalModificacion) {
		this.id = id;
		this.cambio = cambio;
		this.miembroCab = miembroCab;
		this.recomendacion = recomendacion;
		this.comentario = comentario;
		this.enviadoEn = enviadoEn;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoCab", column = @Column(name = "codigoCab", nullable = false)),
			@AttributeOverride(name = "codigoUsuario", column = @Column(name = "codigoUsuario", nullable = false)),
			@AttributeOverride(name = "codigoMiembro", column = @Column(name = "codigoMiembro", nullable = false)),
			@AttributeOverride(name = "codigoCambioMiembro", column = @Column(name = "codigoCambioMiembro", nullable = false)),
			@AttributeOverride(name = "codigoCambio", column = @Column(name = "codigoCambio", nullable = false)) })
	public CambioMiembroId getId() {
		return this.id;
	}

	public void setId(CambioMiembroId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigoCambio", nullable = false, insertable = false, updatable = false)
	public Cambio getCambio() {
		return this.cambio;
	}

	public void setCambio(Cambio cambio) {
		this.cambio = cambio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "codigoCab", referencedColumnName = "codigoCab", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigoUsuario", referencedColumnName = "codigoUsuario", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigoMiembro", referencedColumnName = "codigoMiembro", nullable = false, insertable = false, updatable = false) })
	public MiembroCab getMiembroCab() {
		return this.miembroCab;
	}

	public void setMiembroCab(MiembroCab miembroCab) {
		this.miembroCab = miembroCab;
	}

	@Column(name = "recomendacion", length = 1000)
	public String getRecomendacion() {
		return this.recomendacion;
	}

	public void setRecomendacion(String recomendacion) {
		this.recomendacion = recomendacion;
	}

	@Column(name = "comentario", length = 1000)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "enviadoEn", length = 50)
	public String getEnviadoEn() {
		return this.enviadoEn;
	}

	public void setEnviadoEn(String enviadoEn) {
		this.enviadoEn = enviadoEn;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

}
