package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CambioResponsableId generated by hbm2java
 */
@Embeddable
public class CambioResponsableId implements java.io.Serializable {

	private int codigoCambio;
	private int codigoTecnico;
	private int codigoResponsable;

	public CambioResponsableId() {
	}

	public CambioResponsableId(int codigoCambio, int codigoTecnico,
			int codigoResponsable) {
		this.codigoCambio = codigoCambio;
		this.codigoTecnico = codigoTecnico;
		this.codigoResponsable = codigoResponsable;
	}

	@Column(name = "codigoCambio", nullable = false)
	public int getCodigoCambio() {
		return this.codigoCambio;
	}

	public void setCodigoCambio(int codigoCambio) {
		this.codigoCambio = codigoCambio;
	}

	@Column(name = "codigoTecnico", nullable = false)
	public int getCodigoTecnico() {
		return this.codigoTecnico;
	}

	public void setCodigoTecnico(int codigoTecnico) {
		this.codigoTecnico = codigoTecnico;
	}

	@Column(name = "codigoResponsable", nullable = false)
	public int getCodigoResponsable() {
		return this.codigoResponsable;
	}

	public void setCodigoResponsable(int codigoResponsable) {
		this.codigoResponsable = codigoResponsable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CambioResponsableId))
			return false;
		CambioResponsableId castOther = (CambioResponsableId) other;

		return (this.getCodigoCambio() == castOther.getCodigoCambio())
				&& (this.getCodigoTecnico() == castOther.getCodigoTecnico())
				&& (this.getCodigoResponsable() == castOther
						.getCodigoResponsable());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCambio();
		result = 37 * result + this.getCodigoTecnico();
		result = 37 * result + this.getCodigoResponsable();
		return result;
	}

}
