package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CambioIncidenteId generated by hbm2java
 */
@Embeddable
public class CambioIncidenteId implements java.io.Serializable {

	private int codigoSolicitud;
	private int codigoUsuario;
	private int codigoCambio;

	public CambioIncidenteId() {
	}

	public CambioIncidenteId(int codigoSolicitud, int codigoUsuario,
			int codigoCambio) {
		this.codigoSolicitud = codigoSolicitud;
		this.codigoUsuario = codigoUsuario;
		this.codigoCambio = codigoCambio;
	}

	@Column(name = "codigoSolicitud", nullable = false)
	public int getCodigoSolicitud() {
		return this.codigoSolicitud;
	}

	public void setCodigoSolicitud(int codigoSolicitud) {
		this.codigoSolicitud = codigoSolicitud;
	}

	@Column(name = "codigoUsuario", nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigoCambio", nullable = false)
	public int getCodigoCambio() {
		return this.codigoCambio;
	}

	public void setCodigoCambio(int codigoCambio) {
		this.codigoCambio = codigoCambio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CambioIncidenteId))
			return false;
		CambioIncidenteId castOther = (CambioIncidenteId) other;

		return (this.getCodigoSolicitud() == castOther.getCodigoSolicitud())
				&& (this.getCodigoUsuario() == castOther.getCodigoUsuario())
				&& (this.getCodigoCambio() == castOther.getCodigoCambio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoSolicitud();
		result = 37 * result + this.getCodigoUsuario();
		result = 37 * result + this.getCodigoCambio();
		return result;
	}

}
