package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CambioTareaId generated by hbm2java
 */
@Embeddable
public class CambioTareaId implements java.io.Serializable {

	private int codigoTarea;
	private int codigoCambio;

	public CambioTareaId() {
	}

	public CambioTareaId(int codigoTarea, int codigoCambio) {
		this.codigoTarea = codigoTarea;
		this.codigoCambio = codigoCambio;
	}

	@Column(name = "codigoTarea", nullable = false)
	public int getCodigoTarea() {
		return this.codigoTarea;
	}

	public void setCodigoTarea(int codigoTarea) {
		this.codigoTarea = codigoTarea;
	}

	@Column(name = "codigoCambio", nullable = false)
	public int getCodigoCambio() {
		return this.codigoCambio;
	}

	public void setCodigoCambio(int codigoCambio) {
		this.codigoCambio = codigoCambio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CambioTareaId))
			return false;
		CambioTareaId castOther = (CambioTareaId) other;

		return (this.getCodigoTarea() == castOther.getCodigoTarea())
				&& (this.getCodigoCambio() == castOther.getCodigoCambio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoTarea();
		result = 37 * result + this.getCodigoCambio();
		return result;
	}

}
