package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CambioMiembroId generated by hbm2java
 */
@Embeddable
public class CambioMiembroId implements java.io.Serializable {

	private int codigoCab;
	private int codigoUsuario;
	private int codigoMiembro;
	private int codigoCambioMiembro;
	private int codigoCambio;

	public CambioMiembroId() {
	}

	public CambioMiembroId(int codigoCab, int codigoUsuario, int codigoMiembro,
			int codigoCambioMiembro, int codigoCambio) {
		this.codigoCab = codigoCab;
		this.codigoUsuario = codigoUsuario;
		this.codigoMiembro = codigoMiembro;
		this.codigoCambioMiembro = codigoCambioMiembro;
		this.codigoCambio = codigoCambio;
	}

	@Column(name = "codigoCab", nullable = false)
	public int getCodigoCab() {
		return this.codigoCab;
	}

	public void setCodigoCab(int codigoCab) {
		this.codigoCab = codigoCab;
	}

	@Column(name = "codigoUsuario", nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigoMiembro", nullable = false)
	public int getCodigoMiembro() {
		return this.codigoMiembro;
	}

	public void setCodigoMiembro(int codigoMiembro) {
		this.codigoMiembro = codigoMiembro;
	}

	@Column(name = "codigoCambioMiembro", nullable = false)
	public int getCodigoCambioMiembro() {
		return this.codigoCambioMiembro;
	}

	public void setCodigoCambioMiembro(int codigoCambioMiembro) {
		this.codigoCambioMiembro = codigoCambioMiembro;
	}

	@Column(name = "codigoCambio", nullable = false)
	public int getCodigoCambio() {
		return this.codigoCambio;
	}

	public void setCodigoCambio(int codigoCambio) {
		this.codigoCambio = codigoCambio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CambioMiembroId))
			return false;
		CambioMiembroId castOther = (CambioMiembroId) other;

		return (this.getCodigoCab() == castOther.getCodigoCab())
				&& (this.getCodigoUsuario() == castOther.getCodigoUsuario())
				&& (this.getCodigoMiembro() == castOther.getCodigoMiembro())
				&& (this.getCodigoCambioMiembro() == castOther
						.getCodigoCambioMiembro())
				&& (this.getCodigoCambio() == castOther.getCodigoCambio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCab();
		result = 37 * result + this.getCodigoUsuario();
		result = 37 * result + this.getCodigoMiembro();
		result = 37 * result + this.getCodigoCambioMiembro();
		result = 37 * result + this.getCodigoCambio();
		return result;
	}

}
