package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CategoriaServicio generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIA_SERVICIO", schema = "dbo", catalog = "SISMAV2")
public class CategoriaServicio implements java.io.Serializable {

	private int codigoCategoriaServicio;
	private String nombreCategoriaServicio;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;
	private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
	private Set<CambioServicio> cambioServicios = new HashSet<CambioServicio>(0);
	private Set<ProblemaServicio> problemaServicios = new HashSet<ProblemaServicio>(
			0);

	public CategoriaServicio() {
	}

	public CategoriaServicio(int codigoCategoriaServicio) {
		this.codigoCategoriaServicio = codigoCategoriaServicio;
	}

	public CategoriaServicio(int codigoCategoriaServicio,
			String nombreCategoriaServicio, Integer estado,
			String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion,
			Set<Solicitud> solicituds, Set<CambioServicio> cambioServicios,
			Set<ProblemaServicio> problemaServicios) {
		this.codigoCategoriaServicio = codigoCategoriaServicio;
		this.nombreCategoriaServicio = nombreCategoriaServicio;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
		this.solicituds = solicituds;
		this.cambioServicios = cambioServicios;
		this.problemaServicios = problemaServicios;
	}

	@Id
	@Column(name = "codigoCategoriaServicio", unique = true, nullable = false)
	public int getCodigoCategoriaServicio() {
		return this.codigoCategoriaServicio;
	}

	public void setCodigoCategoriaServicio(int codigoCategoriaServicio) {
		this.codigoCategoriaServicio = codigoCategoriaServicio;
	}

	@Column(name = "nombreCategoriaServicio", length = 50)
	public String getNombreCategoriaServicio() {
		return this.nombreCategoriaServicio;
	}

	public void setNombreCategoriaServicio(String nombreCategoriaServicio) {
		this.nombreCategoriaServicio = nombreCategoriaServicio;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaServicio")
	public Set<Solicitud> getSolicituds() {
		return this.solicituds;
	}

	public void setSolicituds(Set<Solicitud> solicituds) {
		this.solicituds = solicituds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaServicio")
	public Set<CambioServicio> getCambioServicios() {
		return this.cambioServicios;
	}

	public void setCambioServicios(Set<CambioServicio> cambioServicios) {
		this.cambioServicios = cambioServicios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaServicio")
	public Set<ProblemaServicio> getProblemaServicios() {
		return this.problemaServicios;
	}

	public void setProblemaServicios(Set<ProblemaServicio> problemaServicios) {
		this.problemaServicios = problemaServicios;
	}

}
