package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CierreSolicitudId generated by hbm2java
 */
@Embeddable
public class CierreSolicitudId implements java.io.Serializable {

	private int codigoCierre;
	private int codigoSolicitud;
	private int codigoUsuario;

	public CierreSolicitudId() {
	}

	public CierreSolicitudId(int codigoCierre, int codigoSolicitud,
			int codigoUsuario) {
		this.codigoCierre = codigoCierre;
		this.codigoSolicitud = codigoSolicitud;
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigoCierre", nullable = false)
	public int getCodigoCierre() {
		return this.codigoCierre;
	}

	public void setCodigoCierre(int codigoCierre) {
		this.codigoCierre = codigoCierre;
	}

	@Column(name = "codigoSolicitud", nullable = false)
	public int getCodigoSolicitud() {
		return this.codigoSolicitud;
	}

	public void setCodigoSolicitud(int codigoSolicitud) {
		this.codigoSolicitud = codigoSolicitud;
	}

	@Column(name = "codigoUsuario", nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CierreSolicitudId))
			return false;
		CierreSolicitudId castOther = (CierreSolicitudId) other;

		return (this.getCodigoCierre() == castOther.getCodigoCierre())
				&& (this.getCodigoSolicitud() == castOther.getCodigoSolicitud())
				&& (this.getCodigoUsuario() == castOther.getCodigoUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCierre();
		result = 37 * result + this.getCodigoSolicitud();
		result = 37 * result + this.getCodigoUsuario();
		return result;
	}

}
