package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente")
public class Cliente implements java.io.Serializable {

	private Integer id;
	private String idExterno;
	private String  descripcion1;
	private String  descripcion2;
	private String  nroIdentificacion;
	private Integer idDistrito;
	private String  direccion;
	private Integer idEstadoDeuda;
	private String  complemento;
	private Integer saldo;
	private Integer complementoIdMoneda;
	private String fechaSaldo;

	@Id
	//@GeneratedValue(generator = "generator")
	@Column(name = "cliente_id")
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cliente_idExterno")
	public String getIdExterno() {
		return idExterno;
	}
	public void setIdExterno(String idExterno) {
		this.idExterno = idExterno;
	}

	@Column(name = "descripcion1")
	public String getDescripcion1() {
		return descripcion1;
	}
	public void setDescripcion1(String descripcion1) {
		this.descripcion1 = descripcion1;
	}

	@Column(name = "descripcion2")
	public String getDescripcion2() {
		return descripcion2;
	}
	public void setDescripcion2(String descripcion2) {
		this.descripcion2 = descripcion2;
	}

	@Column(name = "nro_identificacion")
	public String getNroIdentificacion() {
		return nroIdentificacion;
	}
	public void setNroIdentificacion(String nroIdentificacion) {
		this.nroIdentificacion = nroIdentificacion;
	}

	@Column(name = "dst_id")
	public Integer getIdDistrito() {
		return idDistrito;
	}
	public void setIdDistrito(Integer idDistrito) {
		this.idDistrito = idDistrito;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return direccion;
	}
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "estado_idDeuda")
	public Integer getIdEstadoDeuda() {
		return idEstadoDeuda;
	}
	public void setIdEstadoDeuda(Integer idEstadoDeuda) {
		this.idEstadoDeuda = idEstadoDeuda;
	}

	@Column(name = "complemento_idMoneda")
	public String getComplemento() {
		return complemento;
	}
	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "saldo")
	public Integer getSaldo() {
		return saldo;
	}
	public void setSaldo(Integer saldo) {
		this.saldo = saldo;
	}

	@Column(name = "complemento_IdMoneda")
	public Integer getComplementoIdMoneda() {
		return complementoIdMoneda;
	}
	public void setComplementoIdMoneda(Integer complementoIdMoneda) {
		this.complementoIdMoneda = complementoIdMoneda;
	}

	@Column(name = "fecha_saldo")
	public String getFechaSaldo() {
		return fechaSaldo;
	}
	public void setFechaSaldo(String fechaSaldo) {
		this.fechaSaldo = fechaSaldo;
	}
	
}
