package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DescripcionOpcion generated by hbm2java
 */
@Entity
@Table(name = "DESCRIPCION_OPCION", schema = "dbo", catalog = "SISMAV2")
public class DescripcionOpcion implements java.io.Serializable {

	private DescripcionOpcionId id;
	private Opcion opcion;
	private String nombre;
	private String descripcion;
	private Integer estado;
	private Integer tipo;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;

	public DescripcionOpcion() {
	}

	public DescripcionOpcion(DescripcionOpcionId id, Opcion opcion) {
		this.id = id;
		this.opcion = opcion;
	}

	public DescripcionOpcion(DescripcionOpcionId id, Opcion opcion,
			String nombre, String descripcion, Integer estado, Integer tipo,
			String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion) {
		this.id = id;
		this.opcion = opcion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.tipo = tipo;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoDescripcionOpcion", column = @Column(name = "codigoDescripcionOpcion", nullable = false)),
			@AttributeOverride(name = "codigoOpcion", column = @Column(name = "codigoOpcion", nullable = false)),
			@AttributeOverride(name = "codigoCategoriaOpcion", column = @Column(name = "codigoCategoriaOpcion", nullable = false)),
			@AttributeOverride(name = "codigoIdioma", column = @Column(name = "codigoIdioma", nullable = false)) })
	public DescripcionOpcionId getId() {
		return this.id;
	}

	public void setId(DescripcionOpcionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "codigoOpcion", referencedColumnName = "codigoOpcion", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigoCategoriaOpcion", referencedColumnName = "codigoCategoriaOpcion", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigoIdioma", referencedColumnName = "codigoIdioma", nullable = false, insertable = false, updatable = false) })
	public Opcion getOpcion() {
		return this.opcion;
	}

	public void setOpcion(Opcion opcion) {
		this.opcion = opcion;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "tipo")
	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

}
