package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DescripcionOpcionId generated by hbm2java
 */
@Embeddable
public class DescripcionOpcionId implements java.io.Serializable {

	private int codigoDescripcionOpcion;
	private int codigoOpcion;
	private int codigoCategoriaOpcion;
	private int codigoIdioma;

	public DescripcionOpcionId() {
	}

	public DescripcionOpcionId(int codigoDescripcionOpcion, int codigoOpcion,
			int codigoCategoriaOpcion, int codigoIdioma) {
		this.codigoDescripcionOpcion = codigoDescripcionOpcion;
		this.codigoOpcion = codigoOpcion;
		this.codigoCategoriaOpcion = codigoCategoriaOpcion;
		this.codigoIdioma = codigoIdioma;
	}

	@Column(name = "codigoDescripcionOpcion", nullable = false)
	public int getCodigoDescripcionOpcion() {
		return this.codigoDescripcionOpcion;
	}

	public void setCodigoDescripcionOpcion(int codigoDescripcionOpcion) {
		this.codigoDescripcionOpcion = codigoDescripcionOpcion;
	}

	@Column(name = "codigoOpcion", nullable = false)
	public int getCodigoOpcion() {
		return this.codigoOpcion;
	}

	public void setCodigoOpcion(int codigoOpcion) {
		this.codigoOpcion = codigoOpcion;
	}

	@Column(name = "codigoCategoriaOpcion", nullable = false)
	public int getCodigoCategoriaOpcion() {
		return this.codigoCategoriaOpcion;
	}

	public void setCodigoCategoriaOpcion(int codigoCategoriaOpcion) {
		this.codigoCategoriaOpcion = codigoCategoriaOpcion;
	}

	@Column(name = "codigoIdioma", nullable = false)
	public int getCodigoIdioma() {
		return this.codigoIdioma;
	}

	public void setCodigoIdioma(int codigoIdioma) {
		this.codigoIdioma = codigoIdioma;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DescripcionOpcionId))
			return false;
		DescripcionOpcionId castOther = (DescripcionOpcionId) other;

		return (this.getCodigoDescripcionOpcion() == castOther
				.getCodigoDescripcionOpcion())
				&& (this.getCodigoOpcion() == castOther.getCodigoOpcion())
				&& (this.getCodigoCategoriaOpcion() == castOther
						.getCodigoCategoriaOpcion())
				&& (this.getCodigoIdioma() == castOther.getCodigoIdioma());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoDescripcionOpcion();
		result = 37 * result + this.getCodigoOpcion();
		result = 37 * result + this.getCodigoCategoriaOpcion();
		result = 37 * result + this.getCodigoIdioma();
		return result;
	}

}
