package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DiaLaborableId generated by hbm2java
 */
@Embeddable
public class DiaLaborableId implements java.io.Serializable {

	private int codigoDiaLaborable;
	private int codigoDia;

	public DiaLaborableId() {
	}

	public DiaLaborableId(int codigoDiaLaborable, int codigoDia) {
		this.codigoDiaLaborable = codigoDiaLaborable;
		this.codigoDia = codigoDia;
	}

	@Column(name = "codigoDiaLaborable", nullable = false)
	public int getCodigoDiaLaborable() {
		return this.codigoDiaLaborable;
	}

	public void setCodigoDiaLaborable(int codigoDiaLaborable) {
		this.codigoDiaLaborable = codigoDiaLaborable;
	}

	@Column(name = "codigoDia", nullable = false)
	public int getCodigoDia() {
		return this.codigoDia;
	}

	public void setCodigoDia(int codigoDia) {
		this.codigoDia = codigoDia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiaLaborableId))
			return false;
		DiaLaborableId castOther = (DiaLaborableId) other;

		return (this.getCodigoDiaLaborable() == castOther
				.getCodigoDiaLaborable())
				&& (this.getCodigoDia() == castOther.getCodigoDia());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoDiaLaborable();
		result = 37 * result + this.getCodigoDia();
		return result;
	}

}
