package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ElementoId generated by hbm2java
 */
@Embeddable
public class ElementoId implements java.io.Serializable {

	private int codigoCategoria;
	private int codigoSubCategoria;
	private int codigoElemento;

	public ElementoId() {
	}

	public ElementoId(int codigoCategoria, int codigoSubCategoria,
			int codigoElemento) {
		this.codigoCategoria = codigoCategoria;
		this.codigoSubCategoria = codigoSubCategoria;
		this.codigoElemento = codigoElemento;
	}

	@Column(name = "codigoCategoria", nullable = false)
	public int getCodigoCategoria() {
		return this.codigoCategoria;
	}

	public void setCodigoCategoria(int codigoCategoria) {
		this.codigoCategoria = codigoCategoria;
	}

	@Column(name = "codigoSubCategoria", nullable = false)
	public int getCodigoSubCategoria() {
		return this.codigoSubCategoria;
	}

	public void setCodigoSubCategoria(int codigoSubCategoria) {
		this.codigoSubCategoria = codigoSubCategoria;
	}

	@Column(name = "codigoElemento", nullable = false)
	public int getCodigoElemento() {
		return this.codigoElemento;
	}

	public void setCodigoElemento(int codigoElemento) {
		this.codigoElemento = codigoElemento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElementoId))
			return false;
		ElementoId castOther = (ElementoId) other;

		return (this.getCodigoCategoria() == castOther.getCodigoCategoria())
				&& (this.getCodigoSubCategoria() == castOther
						.getCodigoSubCategoria())
				&& (this.getCodigoElemento() == castOther.getCodigoElemento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCategoria();
		result = 37 * result + this.getCodigoSubCategoria();
		result = 37 * result + this.getCodigoElemento();
		return result;
	}

}
