package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FuncionDetalleId generated by hbm2java
 */
@Embeddable
public class FuncionDetalleId implements java.io.Serializable {

	private int codigoNivelAcceso;
	private int codigoFuncion;

	public FuncionDetalleId() {
	}

	public FuncionDetalleId(int codigoNivelAcceso, int codigoFuncion) {
		this.codigoNivelAcceso = codigoNivelAcceso;
		this.codigoFuncion = codigoFuncion;
	}

	@Column(name = "codigoNivelAcceso", nullable = false)
	public int getCodigoNivelAcceso() {
		return this.codigoNivelAcceso;
	}

	public void setCodigoNivelAcceso(int codigoNivelAcceso) {
		this.codigoNivelAcceso = codigoNivelAcceso;
	}

	@Column(name = "codigoFuncion", nullable = false)
	public int getCodigoFuncion() {
		return this.codigoFuncion;
	}

	public void setCodigoFuncion(int codigoFuncion) {
		this.codigoFuncion = codigoFuncion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FuncionDetalleId))
			return false;
		FuncionDetalleId castOther = (FuncionDetalleId) other;

		return (this.getCodigoNivelAcceso() == castOther.getCodigoNivelAcceso())
				&& (this.getCodigoFuncion() == castOther.getCodigoFuncion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoNivelAcceso();
		result = 37 * result + this.getCodigoFuncion();
		return result;
	}

}
