package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Impacto generated by hbm2java
 */
@Entity
@Table(name = "IMPACTO", schema = "dbo", catalog = "SISMAV2")
public class Impacto implements java.io.Serializable {

	private int codigoImpacto;
	private String nombreImpacto;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;
	private Set<Problema> problemas = new HashSet<Problema>(0);
	private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
	private Set<Cambio> cambios = new HashSet<Cambio>(0);

	public Impacto() {
	}

	public Impacto(int codigoImpacto) {
		this.codigoImpacto = codigoImpacto;
	}

	public Impacto(int codigoImpacto, String nombreImpacto, Integer estado,
			String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion,
			Set<Problema> problemas, Set<Solicitud> solicituds,
			Set<Cambio> cambios) {
		this.codigoImpacto = codigoImpacto;
		this.nombreImpacto = nombreImpacto;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
		this.problemas = problemas;
		this.solicituds = solicituds;
		this.cambios = cambios;
	}

	@Id
	@Column(name = "codigoImpacto", unique = true, nullable = false)
	public int getCodigoImpacto() {
		return this.codigoImpacto;
	}

	public void setCodigoImpacto(int codigoImpacto) {
		this.codigoImpacto = codigoImpacto;
	}

	@Column(name = "nombreImpacto", length = 50)
	public String getNombreImpacto() {
		return this.nombreImpacto;
	}

	public void setNombreImpacto(String nombreImpacto) {
		this.nombreImpacto = nombreImpacto;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "impacto")
	public Set<Problema> getProblemas() {
		return this.problemas;
	}

	public void setProblemas(Set<Problema> problemas) {
		this.problemas = problemas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "impacto")
	public Set<Solicitud> getSolicituds() {
		return this.solicituds;
	}

	public void setSolicituds(Set<Solicitud> solicituds) {
		this.solicituds = solicituds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "impacto")
	public Set<Cambio> getCambios() {
		return this.cambios;
	}

	public void setCambios(Set<Cambio> cambios) {
		this.cambios = cambios;
	}

}
