package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LoginId generated by hbm2java
 */
@Embeddable
public class LoginId implements java.io.Serializable {

	private int codigoLogin;
	private int codigoUsuario;

	public LoginId() {
	}

	public LoginId(int codigoLogin, int codigoUsuario) {
		this.codigoLogin = codigoLogin;
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigoLogin", nullable = false)
	public int getCodigoLogin() {
		return this.codigoLogin;
	}

	public void setCodigoLogin(int codigoLogin) {
		this.codigoLogin = codigoLogin;
	}

	@Column(name = "codigoUsuario", nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginId))
			return false;
		LoginId castOther = (LoginId) other;

		return (this.getCodigoLogin() == castOther.getCodigoLogin())
				&& (this.getCodigoUsuario() == castOther.getCodigoUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoLogin();
		result = 37 * result + this.getCodigoUsuario();
		return result;
	}

}
