package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NivelAccesoDetalle generated by hbm2java
 */
@Entity
@Table(name = "NIVEL_ACCESO_DETALLE", schema = "dbo", catalog = "SISMAV2")
public class NivelAccesoDetalle implements java.io.Serializable {

	private NivelAccesoDetalleId id;
	private NivelAcceso nivelAcceso;
	private OpcionAccion opcionAccion;
	private String nombre;
	private Integer valor;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;
	private Integer tipoNivel;

	public NivelAccesoDetalle() {
	}

	public NivelAccesoDetalle(NivelAccesoDetalleId id, NivelAcceso nivelAcceso,
			OpcionAccion opcionAccion) {
		this.id = id;
		this.nivelAcceso = nivelAcceso;
		this.opcionAccion = opcionAccion;
	}

	public NivelAccesoDetalle(NivelAccesoDetalleId id, NivelAcceso nivelAcceso,
			OpcionAccion opcionAccion, String nombre, Integer valor,
			Integer estado, String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion,
			Integer tipoNivel) {
		this.id = id;
		this.nivelAcceso = nivelAcceso;
		this.opcionAccion = opcionAccion;
		this.nombre = nombre;
		this.valor = valor;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
		this.tipoNivel = tipoNivel;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoNivelAccesoDetalle", column = @Column(name = "codigoNivelAccesoDetalle", nullable = false)),
			@AttributeOverride(name = "codigoNivelAcceso", column = @Column(name = "codigoNivelAcceso", nullable = false)),
			@AttributeOverride(name = "codigoOpcionAccion", column = @Column(name = "codigoOpcionAccion", nullable = false)),
			@AttributeOverride(name = "codigoOpcion", column = @Column(name = "codigoOpcion", nullable = false)),
			@AttributeOverride(name = "codigoCategoriaOpcion", column = @Column(name = "codigoCategoriaOpcion", nullable = false)),
			@AttributeOverride(name = "codigoIdioma", column = @Column(name = "codigoIdioma", nullable = false)) })
	public NivelAccesoDetalleId getId() {
		return this.id;
	}

	public void setId(NivelAccesoDetalleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigoNivelAcceso", nullable = false, insertable = false, updatable = false)
	public NivelAcceso getNivelAcceso() {
		return this.nivelAcceso;
	}

	public void setNivelAcceso(NivelAcceso nivelAcceso) {
		this.nivelAcceso = nivelAcceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "codigoOpcionAccion", referencedColumnName = "codigoOpcionAccion", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigoOpcion", referencedColumnName = "codigoOpcion", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigoCategoriaOpcion", referencedColumnName = "codigoCategoriaOpcion", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigoIdioma", referencedColumnName = "codigoIdioma", nullable = false, insertable = false, updatable = false) })
	public OpcionAccion getOpcionAccion() {
		return this.opcionAccion;
	}

	public void setOpcionAccion(OpcionAccion opcionAccion) {
		this.opcionAccion = opcionAccion;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "valor")
	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@Column(name = "tipoNivel")
	public Integer getTipoNivel() {
		return this.tipoNivel;
	}

	public void setTipoNivel(Integer tipoNivel) {
		this.tipoNivel = tipoNivel;
	}

}
