package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NivelAcceso generated by hbm2java
 */
@Entity
@Table(name = "NIVEL_ACCESO", schema = "dbo", catalog = "SISMAV2")
public class NivelAcceso implements java.io.Serializable {

	private int codigoNivelAcceso;
	private Opcion opcion;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;
	private Integer nombre;
	private Integer valor;
	private Integer tipoNivel;
	private Integer controlCompleto;
	private Integer ver;
	private Integer agregar;
	private Integer editar;
	private Integer eliminar;
	private Set<FuncionDetalle> funcionDetalles = new HashSet<FuncionDetalle>(0);
	private Set<NivelAccesoDetalle> nivelAccesoDetalles = new HashSet<NivelAccesoDetalle>(
			0);

	public NivelAcceso() {
	}

	public NivelAcceso(int codigoNivelAcceso) {
		this.codigoNivelAcceso = codigoNivelAcceso;
	}

	public NivelAcceso(int codigoNivelAcceso, Opcion opcion, Integer estado,
			String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion,
			Integer nombre, Integer valor, Integer tipoNivel,
			Integer controlCompleto, Integer ver, Integer agregar,
			Integer editar, Integer eliminar,
			Set<FuncionDetalle> funcionDetalles,
			Set<NivelAccesoDetalle> nivelAccesoDetalles) {
		this.codigoNivelAcceso = codigoNivelAcceso;
		this.opcion = opcion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
		this.nombre = nombre;
		this.valor = valor;
		this.tipoNivel = tipoNivel;
		this.controlCompleto = controlCompleto;
		this.ver = ver;
		this.agregar = agregar;
		this.editar = editar;
		this.eliminar = eliminar;
		this.funcionDetalles = funcionDetalles;
		this.nivelAccesoDetalles = nivelAccesoDetalles;
	}

	@Id
	@Column(name = "codigoNivelAcceso", unique = true, nullable = false)
	public int getCodigoNivelAcceso() {
		return this.codigoNivelAcceso;
	}

	public void setCodigoNivelAcceso(int codigoNivelAcceso) {
		this.codigoNivelAcceso = codigoNivelAcceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "codigoOpcion", referencedColumnName = "codigoOpcion"),
			@JoinColumn(name = "codigoCategoriaOpcion", referencedColumnName = "codigoCategoriaOpcion"),
			@JoinColumn(name = "codigoIdioma", referencedColumnName = "codigoIdioma") })
	public Opcion getOpcion() {
		return this.opcion;
	}

	public void setOpcion(Opcion opcion) {
		this.opcion = opcion;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@Column(name = "nombre")
	public Integer getNombre() {
		return this.nombre;
	}

	public void setNombre(Integer nombre) {
		this.nombre = nombre;
	}

	@Column(name = "valor")
	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

	@Column(name = "tipoNivel")
	public Integer getTipoNivel() {
		return this.tipoNivel;
	}

	public void setTipoNivel(Integer tipoNivel) {
		this.tipoNivel = tipoNivel;
	}

	@Column(name = "controlCompleto")
	public Integer getControlCompleto() {
		return this.controlCompleto;
	}

	public void setControlCompleto(Integer controlCompleto) {
		this.controlCompleto = controlCompleto;
	}

	@Column(name = "ver")
	public Integer getVer() {
		return this.ver;
	}

	public void setVer(Integer ver) {
		this.ver = ver;
	}

	@Column(name = "agregar")
	public Integer getAgregar() {
		return this.agregar;
	}

	public void setAgregar(Integer agregar) {
		this.agregar = agregar;
	}

	@Column(name = "editar")
	public Integer getEditar() {
		return this.editar;
	}

	public void setEditar(Integer editar) {
		this.editar = editar;
	}

	@Column(name = "eliminar")
	public Integer getEliminar() {
		return this.eliminar;
	}

	public void setEliminar(Integer eliminar) {
		this.eliminar = eliminar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelAcceso")
	public Set<FuncionDetalle> getFuncionDetalles() {
		return this.funcionDetalles;
	}

	public void setFuncionDetalles(Set<FuncionDetalle> funcionDetalles) {
		this.funcionDetalles = funcionDetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelAcceso")
	public Set<NivelAccesoDetalle> getNivelAccesoDetalles() {
		return this.nivelAccesoDetalles;
	}

	public void setNivelAccesoDetalles(
			Set<NivelAccesoDetalle> nivelAccesoDetalles) {
		this.nivelAccesoDetalles = nivelAccesoDetalles;
	}

}
