package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotaId generated by hbm2java
 */
@Embeddable
public class NotaId implements java.io.Serializable {

	private int codigoNota;
	private int codigoSolicitud;
	private int codigoUsuario;

	public NotaId() {
	}

	public NotaId(int codigoNota, int codigoSolicitud, int codigoUsuario) {
		this.codigoNota = codigoNota;
		this.codigoSolicitud = codigoSolicitud;
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigoNota", nullable = false)
	public int getCodigoNota() {
		return this.codigoNota;
	}

	public void setCodigoNota(int codigoNota) {
		this.codigoNota = codigoNota;
	}

	@Column(name = "codigoSolicitud", nullable = false)
	public int getCodigoSolicitud() {
		return this.codigoSolicitud;
	}

	public void setCodigoSolicitud(int codigoSolicitud) {
		this.codigoSolicitud = codigoSolicitud;
	}

	@Column(name = "codigoUsuario", nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotaId))
			return false;
		NotaId castOther = (NotaId) other;

		return (this.getCodigoNota() == castOther.getCodigoNota())
				&& (this.getCodigoSolicitud() == castOther.getCodigoSolicitud())
				&& (this.getCodigoUsuario() == castOther.getCodigoUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoNota();
		result = 37 * result + this.getCodigoSolicitud();
		result = 37 * result + this.getCodigoUsuario();
		return result;
	}

}
