package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Opcion generated by hbm2java
 */
@Entity
@Table(name = "OPCION", schema = "dbo", catalog = "SISMAV2")
public class Opcion implements java.io.Serializable {

	private OpcionId id;
	private CategoriaOpcion categoriaOpcion;
	private String nombreOpcion;
	private String descripcion;
	private String direccionUrl;
	private Integer tipoOpcion;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;
	private String imagen;
	private Integer opcionAvanzada;
	private Integer codigoOpcionHijo;
	private Set<NivelAcceso> nivelAccesos = new HashSet<NivelAcceso>(0);
	private Set<ElementoReciente> elementoRecientes = new HashSet<ElementoReciente>(
			0);
	private Set<DescripcionOpcion> descripcionOpcions = new HashSet<DescripcionOpcion>(
			0);
	private Set<OpcionAccion> opcionAccions = new HashSet<OpcionAccion>(0);

	public Opcion() {
	}

	public Opcion(OpcionId id, CategoriaOpcion categoriaOpcion) {
		this.id = id;
		this.categoriaOpcion = categoriaOpcion;
	}

	public Opcion(OpcionId id, CategoriaOpcion categoriaOpcion,
			String nombreOpcion, String descripcion, String direccionUrl,
			Integer tipoOpcion, Integer estado, String usuarioCreacion,
			Date fechaCreacion, String terminalCreacion,
			String usuarioModificacion, Date fechaModificacion,
			String terminalModificacion, String imagen, Integer opcionAvanzada,
			Integer codigoOpcionHijo, Set<NivelAcceso> nivelAccesos,
			Set<ElementoReciente> elementoRecientes,
			Set<DescripcionOpcion> descripcionOpcions,
			Set<OpcionAccion> opcionAccions) {
		this.id = id;
		this.categoriaOpcion = categoriaOpcion;
		this.nombreOpcion = nombreOpcion;
		this.descripcion = descripcion;
		this.direccionUrl = direccionUrl;
		this.tipoOpcion = tipoOpcion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
		this.imagen = imagen;
		this.opcionAvanzada = opcionAvanzada;
		this.codigoOpcionHijo = codigoOpcionHijo;
		this.nivelAccesos = nivelAccesos;
		this.elementoRecientes = elementoRecientes;
		this.descripcionOpcions = descripcionOpcions;
		this.opcionAccions = opcionAccions;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoOpcion", column = @Column(name = "codigoOpcion", nullable = false)),
			@AttributeOverride(name = "codigoCategoriaOpcion", column = @Column(name = "codigoCategoriaOpcion", nullable = false)),
			@AttributeOverride(name = "codigoIdioma", column = @Column(name = "codigoIdioma", nullable = false)) })
	public OpcionId getId() {
		return this.id;
	}

	public void setId(OpcionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "codigoCategoriaOpcion", referencedColumnName = "codigoCategoriaOpcion", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigoIdioma", referencedColumnName = "codigoIdioma", nullable = false, insertable = false, updatable = false) })
	public CategoriaOpcion getCategoriaOpcion() {
		return this.categoriaOpcion;
	}

	public void setCategoriaOpcion(CategoriaOpcion categoriaOpcion) {
		this.categoriaOpcion = categoriaOpcion;
	}

	@Column(name = "nombreOpcion", length = 100)
	public String getNombreOpcion() {
		return this.nombreOpcion;
	}

	public void setNombreOpcion(String nombreOpcion) {
		this.nombreOpcion = nombreOpcion;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "direccionUrl", length = 100)
	public String getDireccionUrl() {
		return this.direccionUrl;
	}

	public void setDireccionUrl(String direccionUrl) {
		this.direccionUrl = direccionUrl;
	}

	@Column(name = "tipoOpcion")
	public Integer getTipoOpcion() {
		return this.tipoOpcion;
	}

	public void setTipoOpcion(Integer tipoOpcion) {
		this.tipoOpcion = tipoOpcion;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@Column(name = "imagen", length = 100)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "opcionAvanzada")
	public Integer getOpcionAvanzada() {
		return this.opcionAvanzada;
	}

	public void setOpcionAvanzada(Integer opcionAvanzada) {
		this.opcionAvanzada = opcionAvanzada;
	}

	@Column(name = "codigoOpcionHijo")
	public Integer getCodigoOpcionHijo() {
		return this.codigoOpcionHijo;
	}

	public void setCodigoOpcionHijo(Integer codigoOpcionHijo) {
		this.codigoOpcionHijo = codigoOpcionHijo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcion")
	public Set<NivelAcceso> getNivelAccesos() {
		return this.nivelAccesos;
	}

	public void setNivelAccesos(Set<NivelAcceso> nivelAccesos) {
		this.nivelAccesos = nivelAccesos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcion")
	public Set<ElementoReciente> getElementoRecientes() {
		return this.elementoRecientes;
	}

	public void setElementoRecientes(Set<ElementoReciente> elementoRecientes) {
		this.elementoRecientes = elementoRecientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcion")
	public Set<DescripcionOpcion> getDescripcionOpcions() {
		return this.descripcionOpcions;
	}

	public void setDescripcionOpcions(Set<DescripcionOpcion> descripcionOpcions) {
		this.descripcionOpcions = descripcionOpcions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcion")
	public Set<OpcionAccion> getOpcionAccions() {
		return this.opcionAccions;
	}

	public void setOpcionAccions(Set<OpcionAccion> opcionAccions) {
		this.opcionAccions = opcionAccions;
	}

}
