package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OpcionAccionId generated by hbm2java
 */
@Embeddable
public class OpcionAccionId implements java.io.Serializable {

	private int codigoOpcionAccion;
	private int codigoOpcion;
	private int codigoCategoriaOpcion;
	private int codigoIdioma;

	public OpcionAccionId() {
	}

	public OpcionAccionId(int codigoOpcionAccion, int codigoOpcion,
			int codigoCategoriaOpcion, int codigoIdioma) {
		this.codigoOpcionAccion = codigoOpcionAccion;
		this.codigoOpcion = codigoOpcion;
		this.codigoCategoriaOpcion = codigoCategoriaOpcion;
		this.codigoIdioma = codigoIdioma;
	}

	@Column(name = "codigoOpcionAccion", nullable = false)
	public int getCodigoOpcionAccion() {
		return this.codigoOpcionAccion;
	}

	public void setCodigoOpcionAccion(int codigoOpcionAccion) {
		this.codigoOpcionAccion = codigoOpcionAccion;
	}

	@Column(name = "codigoOpcion", nullable = false)
	public int getCodigoOpcion() {
		return this.codigoOpcion;
	}

	public void setCodigoOpcion(int codigoOpcion) {
		this.codigoOpcion = codigoOpcion;
	}

	@Column(name = "codigoCategoriaOpcion", nullable = false)
	public int getCodigoCategoriaOpcion() {
		return this.codigoCategoriaOpcion;
	}

	public void setCodigoCategoriaOpcion(int codigoCategoriaOpcion) {
		this.codigoCategoriaOpcion = codigoCategoriaOpcion;
	}

	@Column(name = "codigoIdioma", nullable = false)
	public int getCodigoIdioma() {
		return this.codigoIdioma;
	}

	public void setCodigoIdioma(int codigoIdioma) {
		this.codigoIdioma = codigoIdioma;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OpcionAccionId))
			return false;
		OpcionAccionId castOther = (OpcionAccionId) other;

		return (this.getCodigoOpcionAccion() == castOther
				.getCodigoOpcionAccion())
				&& (this.getCodigoOpcion() == castOther.getCodigoOpcion())
				&& (this.getCodigoCategoriaOpcion() == castOther
						.getCodigoCategoriaOpcion())
				&& (this.getCodigoIdioma() == castOther.getCodigoIdioma());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoOpcionAccion();
		result = 37 * result + this.getCodigoOpcion();
		result = 37 * result + this.getCodigoCategoriaOpcion();
		result = 37 * result + this.getCodigoIdioma();
		return result;
	}

}
