package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Organizacion generated by hbm2java
 */
@Entity
@Table(name = "ORGANIZACION", schema = "dbo", catalog = "SISMAV2")
public class Organizacion implements java.io.Serializable {

	private int codigoOrganizacion;
	private String nombreOrganizacion;
	private String descripcion;
	private String direccion1;
	private String direccion2;
	private String direccion3;
	private String ciudad;
	private String codigoPostal;
	private String pais;
	private String correoElectronico;
	private String telefono;
	private String fax;
	private String direccionUrl;
	private byte[] logotipo;
	private Integer activo;
	private String estadoOrganizacion;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Organizacion() {
	}

	public Organizacion(int codigoOrganizacion) {
		this.codigoOrganizacion = codigoOrganizacion;
	}

	public Organizacion(int codigoOrganizacion, String nombreOrganizacion,
			String descripcion, String direccion1, String direccion2,
			String direccion3, String ciudad, String codigoPostal, String pais,
			String correoElectronico, String telefono, String fax,
			String direccionUrl, byte[] logotipo, Integer activo,
			String estadoOrganizacion, Integer estado, String usuarioCreacion,
			Date fechaCreacion, String terminalCreacion,
			String usuarioModificacion, Date fechaModificacion,
			String terminalModificacion, Set<Usuario> usuarios) {
		this.codigoOrganizacion = codigoOrganizacion;
		this.nombreOrganizacion = nombreOrganizacion;
		this.descripcion = descripcion;
		this.direccion1 = direccion1;
		this.direccion2 = direccion2;
		this.direccion3 = direccion3;
		this.ciudad = ciudad;
		this.codigoPostal = codigoPostal;
		this.pais = pais;
		this.correoElectronico = correoElectronico;
		this.telefono = telefono;
		this.fax = fax;
		this.direccionUrl = direccionUrl;
		this.logotipo = logotipo;
		this.activo = activo;
		this.estadoOrganizacion = estadoOrganizacion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "codigoOrganizacion", unique = true, nullable = false)
	public int getCodigoOrganizacion() {
		return this.codigoOrganizacion;
	}

	public void setCodigoOrganizacion(int codigoOrganizacion) {
		this.codigoOrganizacion = codigoOrganizacion;
	}

	@Column(name = "nombreOrganizacion", length = 100)
	public String getNombreOrganizacion() {
		return this.nombreOrganizacion;
	}

	public void setNombreOrganizacion(String nombreOrganizacion) {
		this.nombreOrganizacion = nombreOrganizacion;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "direccion1", length = 100)
	public String getDireccion1() {
		return this.direccion1;
	}

	public void setDireccion1(String direccion1) {
		this.direccion1 = direccion1;
	}

	@Column(name = "direccion2", length = 100)
	public String getDireccion2() {
		return this.direccion2;
	}

	public void setDireccion2(String direccion2) {
		this.direccion2 = direccion2;
	}

	@Column(name = "direccion3", length = 100)
	public String getDireccion3() {
		return this.direccion3;
	}

	public void setDireccion3(String direccion3) {
		this.direccion3 = direccion3;
	}

	@Column(name = "ciudad", length = 100)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "codigoPostal", length = 50)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "pais", length = 50)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "correoElectronico", length = 100)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "telefono", length = 100)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "fax", length = 100)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "direccionUrl", length = 200)
	public String getDireccionUrl() {
		return this.direccionUrl;
	}

	public void setDireccionUrl(String direccionUrl) {
		this.direccionUrl = direccionUrl;
	}

	@Column(name = "logotipo")
	public byte[] getLogotipo() {
		return this.logotipo;
	}

	public void setLogotipo(byte[] logotipo) {
		this.logotipo = logotipo;
	}

	@Column(name = "activo")
	public Integer getActivo() {
		return this.activo;
	}

	public void setActivo(Integer activo) {
		this.activo = activo;
	}

	@Column(name = "estadoOrganizacion", length = 100)
	public String getEstadoOrganizacion() {
		return this.estadoOrganizacion;
	}

	public void setEstadoOrganizacion(String estadoOrganizacion) {
		this.estadoOrganizacion = estadoOrganizacion;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizacion")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
