package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParametroId generated by hbm2java
 */
@Embeddable
public class ParametroId implements java.io.Serializable {

	private int codigoParametro;
	private int codigoCategoria;

	public ParametroId() {
	}

	public ParametroId(int codigoParametro, int codigoCategoria) {
		this.codigoParametro = codigoParametro;
		this.codigoCategoria = codigoCategoria;
	}

	@Column(name = "codigoParametro", nullable = false)
	public int getCodigoParametro() {
		return this.codigoParametro;
	}

	public void setCodigoParametro(int codigoParametro) {
		this.codigoParametro = codigoParametro;
	}

	@Column(name = "codigoCategoria", nullable = false)
	public int getCodigoCategoria() {
		return this.codigoCategoria;
	}

	public void setCodigoCategoria(int codigoCategoria) {
		this.codigoCategoria = codigoCategoria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParametroId))
			return false;
		ParametroId castOther = (ParametroId) other;

		return (this.getCodigoParametro() == castOther.getCodigoParametro())
				&& (this.getCodigoCategoria() == castOther.getCodigoCategoria());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoParametro();
		result = 37 * result + this.getCodigoCategoria();
		return result;
	}

}
