package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProblemaHistorialId generated by hbm2java
 */
@Embeddable
public class ProblemaHistorialId implements java.io.Serializable {

	private int codigoHistorial;
	private int codigoProblema;

	public ProblemaHistorialId() {
	}

	public ProblemaHistorialId(int codigoHistorial, int codigoProblema) {
		this.codigoHistorial = codigoHistorial;
		this.codigoProblema = codigoProblema;
	}

	@Column(name = "codigoHistorial", nullable = false)
	public int getCodigoHistorial() {
		return this.codigoHistorial;
	}

	public void setCodigoHistorial(int codigoHistorial) {
		this.codigoHistorial = codigoHistorial;
	}

	@Column(name = "codigoProblema", nullable = false)
	public int getCodigoProblema() {
		return this.codigoProblema;
	}

	public void setCodigoProblema(int codigoProblema) {
		this.codigoProblema = codigoProblema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProblemaHistorialId))
			return false;
		ProblemaHistorialId castOther = (ProblemaHistorialId) other;

		return (this.getCodigoHistorial() == castOther.getCodigoHistorial())
				&& (this.getCodigoProblema() == castOther.getCodigoProblema());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoHistorial();
		result = 37 * result + this.getCodigoProblema();
		return result;
	}

}
