package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProblemaEntTiempoId generated by hbm2java
 */
@Embeddable
public class ProblemaEntTiempoId implements java.io.Serializable {

	private int codigoEntradaTiempo;
	private int codigoTecnico;
	private int codigoProblema;

	public ProblemaEntTiempoId() {
	}

	public ProblemaEntTiempoId(int codigoEntradaTiempo, int codigoTecnico,
			int codigoProblema) {
		this.codigoEntradaTiempo = codigoEntradaTiempo;
		this.codigoTecnico = codigoTecnico;
		this.codigoProblema = codigoProblema;
	}

	@Column(name = "codigoEntradaTiempo", nullable = false)
	public int getCodigoEntradaTiempo() {
		return this.codigoEntradaTiempo;
	}

	public void setCodigoEntradaTiempo(int codigoEntradaTiempo) {
		this.codigoEntradaTiempo = codigoEntradaTiempo;
	}

	@Column(name = "codigoTecnico", nullable = false)
	public int getCodigoTecnico() {
		return this.codigoTecnico;
	}

	public void setCodigoTecnico(int codigoTecnico) {
		this.codigoTecnico = codigoTecnico;
	}

	@Column(name = "codigoProblema", nullable = false)
	public int getCodigoProblema() {
		return this.codigoProblema;
	}

	public void setCodigoProblema(int codigoProblema) {
		this.codigoProblema = codigoProblema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProblemaEntTiempoId))
			return false;
		ProblemaEntTiempoId castOther = (ProblemaEntTiempoId) other;

		return (this.getCodigoEntradaTiempo() == castOther
				.getCodigoEntradaTiempo())
				&& (this.getCodigoTecnico() == castOther.getCodigoTecnico())
				&& (this.getCodigoProblema() == castOther.getCodigoProblema());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoEntradaTiempo();
		result = 37 * result + this.getCodigoTecnico();
		result = 37 * result + this.getCodigoProblema();
		return result;
	}

}
