package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProblemaTarea generated by hbm2java
 */
@Entity
@Table(name = "PROBLEMA_TAREA", schema = "dbo", catalog = "SISMAV2")
public class ProblemaTarea implements java.io.Serializable {

	private ProblemaTareaId id;
	private Problema problema;
	private String nombreTarea;
	private String descripcionTarea;
	private Date fechaInicioProgramada;
	private Date horaInicioProgramada;
	private Date fechaInicioReal;
	private Date horaInicioReal;
	private Date fechaFinProgramada;
	private Date horaFinProgramada;
	private Date fechaFinReal;
	private Date horaFinReal;
	private Integer tipoTarea;
	private Integer nivel;
	private Integer recordarAntes;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;

	public ProblemaTarea() {
	}

	public ProblemaTarea(ProblemaTareaId id, Problema problema) {
		this.id = id;
		this.problema = problema;
	}

	public ProblemaTarea(ProblemaTareaId id, Problema problema,
			String nombreTarea, String descripcionTarea,
			Date fechaInicioProgramada, Date horaInicioProgramada,
			Date fechaInicioReal, Date horaInicioReal, Date fechaFinProgramada,
			Date horaFinProgramada, Date fechaFinReal, Date horaFinReal,
			Integer tipoTarea, Integer nivel, Integer recordarAntes,
			Integer estado, String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion) {
		this.id = id;
		this.problema = problema;
		this.nombreTarea = nombreTarea;
		this.descripcionTarea = descripcionTarea;
		this.fechaInicioProgramada = fechaInicioProgramada;
		this.horaInicioProgramada = horaInicioProgramada;
		this.fechaInicioReal = fechaInicioReal;
		this.horaInicioReal = horaInicioReal;
		this.fechaFinProgramada = fechaFinProgramada;
		this.horaFinProgramada = horaFinProgramada;
		this.fechaFinReal = fechaFinReal;
		this.horaFinReal = horaFinReal;
		this.tipoTarea = tipoTarea;
		this.nivel = nivel;
		this.recordarAntes = recordarAntes;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoTarea", column = @Column(name = "codigoTarea", nullable = false)),
			@AttributeOverride(name = "codigoProblema", column = @Column(name = "codigoProblema", nullable = false)) })
	public ProblemaTareaId getId() {
		return this.id;
	}

	public void setId(ProblemaTareaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigoProblema", nullable = false, insertable = false, updatable = false)
	public Problema getProblema() {
		return this.problema;
	}

	public void setProblema(Problema problema) {
		this.problema = problema;
	}

	@Column(name = "nombreTarea", length = 100)
	public String getNombreTarea() {
		return this.nombreTarea;
	}

	public void setNombreTarea(String nombreTarea) {
		this.nombreTarea = nombreTarea;
	}

	@Column(name = "descripcionTarea", length = 500)
	public String getDescripcionTarea() {
		return this.descripcionTarea;
	}

	public void setDescripcionTarea(String descripcionTarea) {
		this.descripcionTarea = descripcionTarea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaInicioProgramada", length = 23)
	public Date getFechaInicioProgramada() {
		return this.fechaInicioProgramada;
	}

	public void setFechaInicioProgramada(Date fechaInicioProgramada) {
		this.fechaInicioProgramada = fechaInicioProgramada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "horaInicioProgramada", length = 23)
	public Date getHoraInicioProgramada() {
		return this.horaInicioProgramada;
	}

	public void setHoraInicioProgramada(Date horaInicioProgramada) {
		this.horaInicioProgramada = horaInicioProgramada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaInicioReal", length = 23)
	public Date getFechaInicioReal() {
		return this.fechaInicioReal;
	}

	public void setFechaInicioReal(Date fechaInicioReal) {
		this.fechaInicioReal = fechaInicioReal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "horaInicioReal", length = 23)
	public Date getHoraInicioReal() {
		return this.horaInicioReal;
	}

	public void setHoraInicioReal(Date horaInicioReal) {
		this.horaInicioReal = horaInicioReal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaFinProgramada", length = 23)
	public Date getFechaFinProgramada() {
		return this.fechaFinProgramada;
	}

	public void setFechaFinProgramada(Date fechaFinProgramada) {
		this.fechaFinProgramada = fechaFinProgramada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "horaFinProgramada", length = 23)
	public Date getHoraFinProgramada() {
		return this.horaFinProgramada;
	}

	public void setHoraFinProgramada(Date horaFinProgramada) {
		this.horaFinProgramada = horaFinProgramada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaFinReal", length = 23)
	public Date getFechaFinReal() {
		return this.fechaFinReal;
	}

	public void setFechaFinReal(Date fechaFinReal) {
		this.fechaFinReal = fechaFinReal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "horaFinReal", length = 23)
	public Date getHoraFinReal() {
		return this.horaFinReal;
	}

	public void setHoraFinReal(Date horaFinReal) {
		this.horaFinReal = horaFinReal;
	}

	@Column(name = "tipoTarea")
	public Integer getTipoTarea() {
		return this.tipoTarea;
	}

	public void setTipoTarea(Integer tipoTarea) {
		this.tipoTarea = tipoTarea;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "recordarAntes")
	public Integer getRecordarAntes() {
		return this.recordarAntes;
	}

	public void setRecordarAntes(Integer recordarAntes) {
		this.recordarAntes = recordarAntes;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

}
