package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProblemaServicioId generated by hbm2java
 */
@Embeddable
public class ProblemaServicioId implements java.io.Serializable {

	private int codigoCategoriaServicio;
	private int codigoProblema;

	public ProblemaServicioId() {
	}

	public ProblemaServicioId(int codigoCategoriaServicio, int codigoProblema) {
		this.codigoCategoriaServicio = codigoCategoriaServicio;
		this.codigoProblema = codigoProblema;
	}

	@Column(name = "codigoCategoriaServicio", nullable = false)
	public int getCodigoCategoriaServicio() {
		return this.codigoCategoriaServicio;
	}

	public void setCodigoCategoriaServicio(int codigoCategoriaServicio) {
		this.codigoCategoriaServicio = codigoCategoriaServicio;
	}

	@Column(name = "codigoProblema", nullable = false)
	public int getCodigoProblema() {
		return this.codigoProblema;
	}

	public void setCodigoProblema(int codigoProblema) {
		this.codigoProblema = codigoProblema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProblemaServicioId))
			return false;
		ProblemaServicioId castOther = (ProblemaServicioId) other;

		return (this.getCodigoCategoriaServicio() == castOther
				.getCodigoCategoriaServicio())
				&& (this.getCodigoProblema() == castOther.getCodigoProblema());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCategoriaServicio();
		result = 37 * result + this.getCodigoProblema();
		return result;
	}

}
