package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProblemaNotaId generated by hbm2java
 */
@Embeddable
public class ProblemaNotaId implements java.io.Serializable {

	private int codigoNota;
	private int codigoProblema;

	public ProblemaNotaId() {
	}

	public ProblemaNotaId(int codigoNota, int codigoProblema) {
		this.codigoNota = codigoNota;
		this.codigoProblema = codigoProblema;
	}

	@Column(name = "codigoNota", nullable = false)
	public int getCodigoNota() {
		return this.codigoNota;
	}

	public void setCodigoNota(int codigoNota) {
		this.codigoNota = codigoNota;
	}

	@Column(name = "codigoProblema", nullable = false)
	public int getCodigoProblema() {
		return this.codigoProblema;
	}

	public void setCodigoProblema(int codigoProblema) {
		this.codigoProblema = codigoProblema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProblemaNotaId))
			return false;
		ProblemaNotaId castOther = (ProblemaNotaId) other;

		return (this.getCodigoNota() == castOther.getCodigoNota())
				&& (this.getCodigoProblema() == castOther.getCodigoProblema());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoNota();
		result = 37 * result + this.getCodigoProblema();
		return result;
	}

}
