package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProblemaProductoId generated by hbm2java
 */
@Embeddable
public class ProblemaProductoId implements java.io.Serializable {

	private int codigoProducto;
	private int codigoProblema;

	public ProblemaProductoId() {
	}

	public ProblemaProductoId(int codigoProducto, int codigoProblema) {
		this.codigoProducto = codigoProducto;
		this.codigoProblema = codigoProblema;
	}

	@Column(name = "codigoProducto", nullable = false)
	public int getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(int codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	@Column(name = "codigoProblema", nullable = false)
	public int getCodigoProblema() {
		return this.codigoProblema;
	}

	public void setCodigoProblema(int codigoProblema) {
		this.codigoProblema = codigoProblema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProblemaProductoId))
			return false;
		ProblemaProductoId castOther = (ProblemaProductoId) other;

		return (this.getCodigoProducto() == castOther.getCodigoProducto())
				&& (this.getCodigoProblema() == castOther.getCodigoProblema());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoProducto();
		result = 37 * result + this.getCodigoProblema();
		return result;
	}

}
