package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProblemaAdjuntoId generated by hbm2java
 */
@Embeddable
public class ProblemaAdjuntoId implements java.io.Serializable {

	private int codigoAdjunto;
	private int codigoProblema;

	public ProblemaAdjuntoId() {
	}

	public ProblemaAdjuntoId(int codigoAdjunto, int codigoProblema) {
		this.codigoAdjunto = codigoAdjunto;
		this.codigoProblema = codigoProblema;
	}

	@Column(name = "codigoAdjunto", nullable = false)
	public int getCodigoAdjunto() {
		return this.codigoAdjunto;
	}

	public void setCodigoAdjunto(int codigoAdjunto) {
		this.codigoAdjunto = codigoAdjunto;
	}

	@Column(name = "codigoProblema", nullable = false)
	public int getCodigoProblema() {
		return this.codigoProblema;
	}

	public void setCodigoProblema(int codigoProblema) {
		this.codigoProblema = codigoProblema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProblemaAdjuntoId))
			return false;
		ProblemaAdjuntoId castOther = (ProblemaAdjuntoId) other;

		return (this.getCodigoAdjunto() == castOther.getCodigoAdjunto())
				&& (this.getCodigoProblema() == castOther.getCodigoProblema());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoAdjunto();
		result = 37 * result + this.getCodigoProblema();
		return result;
	}

}
