package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductoProveedor generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTO_PROVEEDOR", schema = "dbo", catalog = "SISMAV2")
public class ProductoProveedor implements java.io.Serializable {

	private ProductoProveedorId id;
	private Producto producto;
	private Proveedor proveedor;
	private BigDecimal precio;
	private BigDecimal tipoImpositivo;
	private Integer periodoGarantiaAnio;
	private Integer periodoGarantiaMes;
	private String comentario;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;

	public ProductoProveedor() {
	}

	public ProductoProveedor(ProductoProveedorId id, Producto producto,
			Proveedor proveedor) {
		this.id = id;
		this.producto = producto;
		this.proveedor = proveedor;
	}

	public ProductoProveedor(ProductoProveedorId id, Producto producto,
			Proveedor proveedor, BigDecimal precio, BigDecimal tipoImpositivo,
			Integer periodoGarantiaAnio, Integer periodoGarantiaMes,
			String comentario, Integer estado, String usuarioCreacion,
			Date fechaCreacion, String terminalCreacion,
			String usuarioModificacion, Date fechaModificacion,
			String terminalModificacion) {
		this.id = id;
		this.producto = producto;
		this.proveedor = proveedor;
		this.precio = precio;
		this.tipoImpositivo = tipoImpositivo;
		this.periodoGarantiaAnio = periodoGarantiaAnio;
		this.periodoGarantiaMes = periodoGarantiaMes;
		this.comentario = comentario;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoProveedorMantenimiento", column = @Column(name = "codigoProveedorMantenimiento", nullable = false)),
			@AttributeOverride(name = "codigoProducto", column = @Column(name = "codigoProducto", nullable = false)),
			@AttributeOverride(name = "codigoProveedor", column = @Column(name = "codigoProveedor", nullable = false)) })
	public ProductoProveedorId getId() {
		return this.id;
	}

	public void setId(ProductoProveedorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigoProducto", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigoProveedor", nullable = false, insertable = false, updatable = false)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@Column(name = "precio", precision = 10)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "tipoImpositivo", precision = 10)
	public BigDecimal getTipoImpositivo() {
		return this.tipoImpositivo;
	}

	public void setTipoImpositivo(BigDecimal tipoImpositivo) {
		this.tipoImpositivo = tipoImpositivo;
	}

	@Column(name = "periodoGarantiaAnio")
	public Integer getPeriodoGarantiaAnio() {
		return this.periodoGarantiaAnio;
	}

	public void setPeriodoGarantiaAnio(Integer periodoGarantiaAnio) {
		this.periodoGarantiaAnio = periodoGarantiaAnio;
	}

	@Column(name = "periodoGarantiaMes")
	public Integer getPeriodoGarantiaMes() {
		return this.periodoGarantiaMes;
	}

	public void setPeriodoGarantiaMes(Integer periodoGarantiaMes) {
		this.periodoGarantiaMes = periodoGarantiaMes;
	}

	@Column(name = "comentario", length = 5000)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

}
