package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Servidor generated by hbm2java
 */
@Entity
@Table(name = "SERVIDOR", schema = "dbo", catalog = "SISMAV2")
public class Servidor implements java.io.Serializable {

	private int codigoServidor;
	private String nombreServidor;
	private String direccionIp;
	private String nombreUsuario;
	private String password;
	private String direccionCorreo;
	private String tipoCorreo;
	private String puerto;
	private Integer recogerCorreo;
	private Integer tipo;
	private Integer tipoServidor;
	private String nombreServidorAlternativo;
	private String direccionIpAlternativa;
	private Integer requiereAutenticacion;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;

	public Servidor() {
	}

	public Servidor(int codigoServidor) {
		this.codigoServidor = codigoServidor;
	}

	public Servidor(int codigoServidor, String nombreServidor,
			String direccionIp, String nombreUsuario, String password,
			String direccionCorreo, String tipoCorreo, String puerto,
			Integer recogerCorreo, Integer tipo, Integer tipoServidor,
			String nombreServidorAlternativo, String direccionIpAlternativa,
			Integer requiereAutenticacion, Integer estado,
			String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion) {
		this.codigoServidor = codigoServidor;
		this.nombreServidor = nombreServidor;
		this.direccionIp = direccionIp;
		this.nombreUsuario = nombreUsuario;
		this.password = password;
		this.direccionCorreo = direccionCorreo;
		this.tipoCorreo = tipoCorreo;
		this.puerto = puerto;
		this.recogerCorreo = recogerCorreo;
		this.tipo = tipo;
		this.tipoServidor = tipoServidor;
		this.nombreServidorAlternativo = nombreServidorAlternativo;
		this.direccionIpAlternativa = direccionIpAlternativa;
		this.requiereAutenticacion = requiereAutenticacion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
	}

	@Id
	@Column(name = "codigoServidor", unique = true, nullable = false)
	public int getCodigoServidor() {
		return this.codigoServidor;
	}

	public void setCodigoServidor(int codigoServidor) {
		this.codigoServidor = codigoServidor;
	}

	@Column(name = "nombreServidor", length = 100)
	public String getNombreServidor() {
		return this.nombreServidor;
	}

	public void setNombreServidor(String nombreServidor) {
		this.nombreServidor = nombreServidor;
	}

	@Column(name = "direccionIp", length = 30)
	public String getDireccionIp() {
		return this.direccionIp;
	}

	public void setDireccionIp(String direccionIp) {
		this.direccionIp = direccionIp;
	}

	@Column(name = "nombreUsuario", length = 50)
	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "direccionCorreo", length = 200)
	public String getDireccionCorreo() {
		return this.direccionCorreo;
	}

	public void setDireccionCorreo(String direccionCorreo) {
		this.direccionCorreo = direccionCorreo;
	}

	@Column(name = "tipoCorreo", length = 20)
	public String getTipoCorreo() {
		return this.tipoCorreo;
	}

	public void setTipoCorreo(String tipoCorreo) {
		this.tipoCorreo = tipoCorreo;
	}

	@Column(name = "puerto", length = 10)
	public String getPuerto() {
		return this.puerto;
	}

	public void setPuerto(String puerto) {
		this.puerto = puerto;
	}

	@Column(name = "recogerCorreo")
	public Integer getRecogerCorreo() {
		return this.recogerCorreo;
	}

	public void setRecogerCorreo(Integer recogerCorreo) {
		this.recogerCorreo = recogerCorreo;
	}

	@Column(name = "tipo")
	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	@Column(name = "tipoServidor")
	public Integer getTipoServidor() {
		return this.tipoServidor;
	}

	public void setTipoServidor(Integer tipoServidor) {
		this.tipoServidor = tipoServidor;
	}

	@Column(name = "nombreServidorAlternativo", length = 100)
	public String getNombreServidorAlternativo() {
		return this.nombreServidorAlternativo;
	}

	public void setNombreServidorAlternativo(String nombreServidorAlternativo) {
		this.nombreServidorAlternativo = nombreServidorAlternativo;
	}

	@Column(name = "direccionIpAlternativa", length = 30)
	public String getDireccionIpAlternativa() {
		return this.direccionIpAlternativa;
	}

	public void setDireccionIpAlternativa(String direccionIpAlternativa) {
		this.direccionIpAlternativa = direccionIpAlternativa;
	}

	@Column(name = "requiereAutenticacion")
	public Integer getRequiereAutenticacion() {
		return this.requiereAutenticacion;
	}

	public void setRequiereAutenticacion(Integer requiereAutenticacion) {
		this.requiereAutenticacion = requiereAutenticacion;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

}
