package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sitio generated by hbm2java
 */
@Entity
@Table(name = "SITIO", schema = "dbo", catalog = "SISMAV2")
public class Sitio implements java.io.Serializable {

	private int codigoSitio;
	private String nombreSitio;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;
	private Set<DiaFestivo> diaFestivos = new HashSet<DiaFestivo>(0);
	private Set<Problema> problemas = new HashSet<Problema>(0);
	private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
	private Set<TecnicoSitio> tecnicoSitios = new HashSet<TecnicoSitio>(0);
	private Set<DiaLaborable> diaLaborables = new HashSet<DiaLaborable>(0);
	private Set<Cambio> cambios = new HashSet<Cambio>(0);
	private Set<Departamento> departamentos = new HashSet<Departamento>(0);

	public Sitio() {
	}

	public Sitio(int codigoSitio) {
		this.codigoSitio = codigoSitio;
	}

	public Sitio(int codigoSitio, String nombreSitio, Integer estado,
			String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion,
			Set<DiaFestivo> diaFestivos, Set<Problema> problemas,
			Set<Solicitud> solicituds, Set<TecnicoSitio> tecnicoSitios,
			Set<DiaLaborable> diaLaborables, Set<Cambio> cambios,
			Set<Departamento> departamentos) {
		this.codigoSitio = codigoSitio;
		this.nombreSitio = nombreSitio;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
		this.diaFestivos = diaFestivos;
		this.problemas = problemas;
		this.solicituds = solicituds;
		this.tecnicoSitios = tecnicoSitios;
		this.diaLaborables = diaLaborables;
		this.cambios = cambios;
		this.departamentos = departamentos;
	}

	@Id
	@Column(name = "codigoSitio", unique = true, nullable = false)
	public int getCodigoSitio() {
		return this.codigoSitio;
	}

	public void setCodigoSitio(int codigoSitio) {
		this.codigoSitio = codigoSitio;
	}

	@Column(name = "nombreSitio", length = 50)
	public String getNombreSitio() {
		return this.nombreSitio;
	}

	public void setNombreSitio(String nombreSitio) {
		this.nombreSitio = nombreSitio;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sitio")
	public Set<DiaFestivo> getDiaFestivos() {
		return this.diaFestivos;
	}

	public void setDiaFestivos(Set<DiaFestivo> diaFestivos) {
		this.diaFestivos = diaFestivos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sitio")
	public Set<Problema> getProblemas() {
		return this.problemas;
	}

	public void setProblemas(Set<Problema> problemas) {
		this.problemas = problemas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sitio")
	public Set<Solicitud> getSolicituds() {
		return this.solicituds;
	}

	public void setSolicituds(Set<Solicitud> solicituds) {
		this.solicituds = solicituds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sitio")
	public Set<TecnicoSitio> getTecnicoSitios() {
		return this.tecnicoSitios;
	}

	public void setTecnicoSitios(Set<TecnicoSitio> tecnicoSitios) {
		this.tecnicoSitios = tecnicoSitios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sitio")
	public Set<DiaLaborable> getDiaLaborables() {
		return this.diaLaborables;
	}

	public void setDiaLaborables(Set<DiaLaborable> diaLaborables) {
		this.diaLaborables = diaLaborables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sitio")
	public Set<Cambio> getCambios() {
		return this.cambios;
	}

	public void setCambios(Set<Cambio> cambios) {
		this.cambios = cambios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sitio")
	public Set<Departamento> getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set<Departamento> departamentos) {
		this.departamentos = departamentos;
	}

}
