package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SolicitudCorreoId generated by hbm2java
 */
@Embeddable
public class SolicitudCorreoId implements java.io.Serializable {

	private int codigoCorreo;
	private int codigoSolicitud;
	private int codigoUsuario;

	public SolicitudCorreoId() {
	}

	public SolicitudCorreoId(int codigoCorreo, int codigoSolicitud,
			int codigoUsuario) {
		this.codigoCorreo = codigoCorreo;
		this.codigoSolicitud = codigoSolicitud;
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigoCorreo", nullable = false)
	public int getCodigoCorreo() {
		return this.codigoCorreo;
	}

	public void setCodigoCorreo(int codigoCorreo) {
		this.codigoCorreo = codigoCorreo;
	}

	@Column(name = "codigoSolicitud", nullable = false)
	public int getCodigoSolicitud() {
		return this.codigoSolicitud;
	}

	public void setCodigoSolicitud(int codigoSolicitud) {
		this.codigoSolicitud = codigoSolicitud;
	}

	@Column(name = "codigoUsuario", nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SolicitudCorreoId))
			return false;
		SolicitudCorreoId castOther = (SolicitudCorreoId) other;

		return (this.getCodigoCorreo() == castOther.getCodigoCorreo())
				&& (this.getCodigoSolicitud() == castOther.getCodigoSolicitud())
				&& (this.getCodigoUsuario() == castOther.getCodigoUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCorreo();
		result = 37 * result + this.getCodigoSolicitud();
		result = 37 * result + this.getCodigoUsuario();
		return result;
	}

}
