package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SolicitudHistorialId generated by hbm2java
 */
@Embeddable
public class SolicitudHistorialId implements java.io.Serializable {

	private int codigoHistorial;
	private int codigoSolicitud;
	private int codigoUsuario;

	public SolicitudHistorialId() {
	}

	public SolicitudHistorialId(int codigoHistorial, int codigoSolicitud,
			int codigoUsuario) {
		this.codigoHistorial = codigoHistorial;
		this.codigoSolicitud = codigoSolicitud;
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigoHistorial", nullable = false)
	public int getCodigoHistorial() {
		return this.codigoHistorial;
	}

	public void setCodigoHistorial(int codigoHistorial) {
		this.codigoHistorial = codigoHistorial;
	}

	@Column(name = "codigoSolicitud", nullable = false)
	public int getCodigoSolicitud() {
		return this.codigoSolicitud;
	}

	public void setCodigoSolicitud(int codigoSolicitud) {
		this.codigoSolicitud = codigoSolicitud;
	}

	@Column(name = "codigoUsuario", nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SolicitudHistorialId))
			return false;
		SolicitudHistorialId castOther = (SolicitudHistorialId) other;

		return (this.getCodigoHistorial() == castOther.getCodigoHistorial())
				&& (this.getCodigoSolicitud() == castOther.getCodigoSolicitud())
				&& (this.getCodigoUsuario() == castOther.getCodigoUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoHistorial();
		result = 37 * result + this.getCodigoSolicitud();
		result = 37 * result + this.getCodigoUsuario();
		return result;
	}

}
