package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolicitudAprobacion generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUD_APROBACION", schema = "dbo", catalog = "SISMAV2")
public class SolicitudAprobacion implements java.io.Serializable {

	private SolicitudAprobacionId id;
	private SolicitudResponsable solicitudResponsable;
	private Usuario usuario;
	private Date fechaEnvio;
	private Date fechaRespuesta;
	private Integer estadoAprobacion;
	private Integer estado;
	private String descripcion;
	private Date fechaCreacion;
	private String usuarioCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;

	public SolicitudAprobacion() {
	}

	public SolicitudAprobacion(SolicitudResponsable solicitudResponsable,
			Usuario usuario) {
		this.solicitudResponsable = solicitudResponsable;
		this.usuario = usuario;
	}

	public SolicitudAprobacion(SolicitudResponsable solicitudResponsable,
			Usuario usuario, Date fechaEnvio, Date fechaRespuesta,
			Integer estadoAprobacion, Integer estado, String descripcion,
			Date fechaCreacion, String usuarioCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion) {
		this.solicitudResponsable = solicitudResponsable;
		this.usuario = usuario;
		this.fechaEnvio = fechaEnvio;
		this.fechaRespuesta = fechaRespuesta;
		this.estadoAprobacion = estadoAprobacion;
		this.estado = estado;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCreacion = usuarioCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoSolicitud", column = @Column(name = "codigoSolicitud", nullable = false)),
			@AttributeOverride(name = "codigoSolicitudResponsable", column = @Column(name = "codigoSolicitudResponsable", nullable = false)),
			@AttributeOverride(name = "codigoUsuario", column = @Column(name = "codigoUsuario", nullable = false)),
			@AttributeOverride(name = "codigoTecnico", column = @Column(name = "codigoTecnico", nullable = false)) })
	public SolicitudAprobacionId getId() {
		return this.id;
	}

	public void setId(SolicitudAprobacionId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public SolicitudResponsable getSolicitudResponsable() {
		return this.solicitudResponsable;
	}

	public void setSolicitudResponsable(
			SolicitudResponsable solicitudResponsable) {
		this.solicitudResponsable = solicitudResponsable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigoUsuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaEnvio", length = 23)
	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaRespuesta", length = 23)
	public Date getFechaRespuesta() {
		return this.fechaRespuesta;
	}

	public void setFechaRespuesta(Date fechaRespuesta) {
		this.fechaRespuesta = fechaRespuesta;
	}

	@Column(name = "estadoAprobacion")
	public Integer getEstadoAprobacion() {
		return this.estadoAprobacion;
	}

	public void setEstadoAprobacion(Integer estadoAprobacion) {
		this.estadoAprobacion = estadoAprobacion;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

}
