package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solucion generated by hbm2java
 */
@Entity
@Table(name = "SOLUCION", schema = "dbo", catalog = "SISMAV2")
public class Solucion implements java.io.Serializable {

	private int codigoSolucion;
	private Tema tema;
	private String titulo;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private String terminalModificacion;
	private Date fechaModificacion;
	private String contenido;
	private String palabrasClave;
	private String comentarios;
	private Integer publica;
	private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
	private Set<Problema> problemasForCodigoSolucionAlternativa = new HashSet<Problema>(
			0);
	private Set<Problema> problemasForCodigoSolucion = new HashSet<Problema>(0);

	public Solucion() {
	}

	public Solucion(int codigoSolucion) {
		this.codigoSolucion = codigoSolucion;
	}

	public Solucion(int codigoSolucion, Tema tema, String titulo,
			Integer estado, String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			String terminalModificacion, Date fechaModificacion,
			String contenido, String palabrasClave, String comentarios,
			Integer publica, Set<Solicitud> solicituds,
			Set<Problema> problemasForCodigoSolucionAlternativa,
			Set<Problema> problemasForCodigoSolucion) {
		this.codigoSolucion = codigoSolucion;
		this.tema = tema;
		this.titulo = titulo;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.terminalModificacion = terminalModificacion;
		this.fechaModificacion = fechaModificacion;
		this.contenido = contenido;
		this.palabrasClave = palabrasClave;
		this.comentarios = comentarios;
		this.publica = publica;
		this.solicituds = solicituds;
		this.problemasForCodigoSolucionAlternativa = problemasForCodigoSolucionAlternativa;
		this.problemasForCodigoSolucion = problemasForCodigoSolucion;
	}

	@Id
	@Column(name = "codigoSolucion", unique = true, nullable = false)
	public int getCodigoSolucion() {
		return this.codigoSolucion;
	}

	public void setCodigoSolucion(int codigoSolucion) {
		this.codigoSolucion = codigoSolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigoTema")
	public Tema getTema() {
		return this.tema;
	}

	public void setTema(Tema tema) {
		this.tema = tema;
	}

	@Column(name = "titulo", length = 100)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "contenido", length = 5000)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	@Column(name = "palabrasClave", length = 100)
	public String getPalabrasClave() {
		return this.palabrasClave;
	}

	public void setPalabrasClave(String palabrasClave) {
		this.palabrasClave = palabrasClave;
	}

	@Column(name = "comentarios", length = 500)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "publica")
	public Integer getPublica() {
		return this.publica;
	}

	public void setPublica(Integer publica) {
		this.publica = publica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solucion")
	public Set<Solicitud> getSolicituds() {
		return this.solicituds;
	}

	public void setSolicituds(Set<Solicitud> solicituds) {
		this.solicituds = solicituds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solucionByCodigoSolucionAlternativa")
	public Set<Problema> getProblemasForCodigoSolucionAlternativa() {
		return this.problemasForCodigoSolucionAlternativa;
	}

	public void setProblemasForCodigoSolucionAlternativa(
			Set<Problema> problemasForCodigoSolucionAlternativa) {
		this.problemasForCodigoSolucionAlternativa = problemasForCodigoSolucionAlternativa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solucionByCodigoSolucion")
	public Set<Problema> getProblemasForCodigoSolucion() {
		return this.problemasForCodigoSolucion;
	}

	public void setProblemasForCodigoSolucion(
			Set<Problema> problemasForCodigoSolucion) {
		this.problemasForCodigoSolucion = problemasForCodigoSolucion;
	}

}
