package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubCategoriaId generated by hbm2java
 */
@Embeddable
public class SubCategoriaId implements java.io.Serializable {

	private int codigoCategoria;
	private int codigoSubCategoria;

	public SubCategoriaId() {
	}

	public SubCategoriaId(int codigoCategoria, int codigoSubCategoria) {
		this.codigoCategoria = codigoCategoria;
		this.codigoSubCategoria = codigoSubCategoria;
	}

	@Column(name = "codigoCategoria", nullable = false)
	public int getCodigoCategoria() {
		return this.codigoCategoria;
	}

	public void setCodigoCategoria(int codigoCategoria) {
		this.codigoCategoria = codigoCategoria;
	}

	@Column(name = "codigoSubCategoria", nullable = false)
	public int getCodigoSubCategoria() {
		return this.codigoSubCategoria;
	}

	public void setCodigoSubCategoria(int codigoSubCategoria) {
		this.codigoSubCategoria = codigoSubCategoria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubCategoriaId))
			return false;
		SubCategoriaId castOther = (SubCategoriaId) other;

		return (this.getCodigoCategoria() == castOther.getCodigoCategoria())
				&& (this.getCodigoSubCategoria() == castOther
						.getCodigoSubCategoria());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCategoria();
		result = 37 * result + this.getCodigoSubCategoria();
		return result;
	}

}
