package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TareaId generated by hbm2java
 */
@Embeddable
public class TareaId implements java.io.Serializable {

	private int codigoTarea;
	private int codigoSolicitud;
	private int codigoUsuario;
	private int codigoTecnico;

	public TareaId() {
	}

	public TareaId(int codigoTarea, int codigoSolicitud, int codigoUsuario,
			int codigoTecnico) {
		this.codigoTarea = codigoTarea;
		this.codigoSolicitud = codigoSolicitud;
		this.codigoUsuario = codigoUsuario;
		this.codigoTecnico = codigoTecnico;
	}

	@Column(name = "codigoTarea", nullable = false)
	public int getCodigoTarea() {
		return this.codigoTarea;
	}

	public void setCodigoTarea(int codigoTarea) {
		this.codigoTarea = codigoTarea;
	}

	@Column(name = "codigoSolicitud", nullable = false)
	public int getCodigoSolicitud() {
		return this.codigoSolicitud;
	}

	public void setCodigoSolicitud(int codigoSolicitud) {
		this.codigoSolicitud = codigoSolicitud;
	}

	@Column(name = "codigoUsuario", nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigoTecnico", nullable = false)
	public int getCodigoTecnico() {
		return this.codigoTecnico;
	}

	public void setCodigoTecnico(int codigoTecnico) {
		this.codigoTecnico = codigoTecnico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TareaId))
			return false;
		TareaId castOther = (TareaId) other;

		return (this.getCodigoTarea() == castOther.getCodigoTarea())
				&& (this.getCodigoSolicitud() == castOther.getCodigoSolicitud())
				&& (this.getCodigoUsuario() == castOther.getCodigoUsuario())
				&& (this.getCodigoTecnico() == castOther.getCodigoTecnico());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoTarea();
		result = 37 * result + this.getCodigoSolicitud();
		result = 37 * result + this.getCodigoUsuario();
		result = 37 * result + this.getCodigoTecnico();
		return result;
	}

}
