package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tarea generated by hbm2java
 */
@Entity
@Table(name = "TAREA", schema = "dbo", catalog = "SISMAV2")
public class Tarea implements java.io.Serializable {

	private TareaId id;
	private Solicitud solicitud;
	private Tecnico tecnico;
	private String nombreTarea;
	private String descripcionTarea;
	private Date fechaInicioProgramada;
	private Date fechaFinReal;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;
	private Integer tipoTarea;
	private Integer nivel;
	private Integer horaInicioProgramada;
	private Integer horaFinReal;
	private Integer horaInicioReal;
	private Date fechaInicioReal;
	private Date fechaFinProgramada;
	private Integer horaFinProgramada;
	private Integer recordarAntes;

	public Tarea() {
	}

	public Tarea(TareaId id, Solicitud solicitud, Tecnico tecnico) {
		this.id = id;
		this.solicitud = solicitud;
		this.tecnico = tecnico;
	}

	public Tarea(TareaId id, Solicitud solicitud, Tecnico tecnico,
			String nombreTarea, String descripcionTarea,
			Date fechaInicioProgramada, Date fechaFinReal, Integer estado,
			String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion,
			Integer tipoTarea, Integer nivel, Integer horaInicioProgramada,
			Integer horaFinReal, Integer horaInicioReal, Date fechaInicioReal,
			Date fechaFinProgramada, Integer horaFinProgramada,
			Integer recordarAntes) {
		this.id = id;
		this.solicitud = solicitud;
		this.tecnico = tecnico;
		this.nombreTarea = nombreTarea;
		this.descripcionTarea = descripcionTarea;
		this.fechaInicioProgramada = fechaInicioProgramada;
		this.fechaFinReal = fechaFinReal;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
		this.tipoTarea = tipoTarea;
		this.nivel = nivel;
		this.horaInicioProgramada = horaInicioProgramada;
		this.horaFinReal = horaFinReal;
		this.horaInicioReal = horaInicioReal;
		this.fechaInicioReal = fechaInicioReal;
		this.fechaFinProgramada = fechaFinProgramada;
		this.horaFinProgramada = horaFinProgramada;
		this.recordarAntes = recordarAntes;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoTarea", column = @Column(name = "codigoTarea", nullable = false)),
			@AttributeOverride(name = "codigoSolicitud", column = @Column(name = "codigoSolicitud", nullable = false)),
			@AttributeOverride(name = "codigoUsuario", column = @Column(name = "codigoUsuario", nullable = false)),
			@AttributeOverride(name = "codigoTecnico", column = @Column(name = "codigoTecnico", nullable = false)) })
	public TareaId getId() {
		return this.id;
	}

	public void setId(TareaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "codigoSolicitud", referencedColumnName = "codigoSolicitud", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigoUsuario", referencedColumnName = "codigoUsuario", nullable = false, insertable = false, updatable = false) })
	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigoTecnico", nullable = false, insertable = false, updatable = false)
	public Tecnico getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
	}

	@Column(name = "nombreTarea", length = 50)
	public String getNombreTarea() {
		return this.nombreTarea;
	}

	public void setNombreTarea(String nombreTarea) {
		this.nombreTarea = nombreTarea;
	}

	@Column(name = "descripcionTarea", length = 500)
	public String getDescripcionTarea() {
		return this.descripcionTarea;
	}

	public void setDescripcionTarea(String descripcionTarea) {
		this.descripcionTarea = descripcionTarea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaInicioProgramada", length = 23)
	public Date getFechaInicioProgramada() {
		return this.fechaInicioProgramada;
	}

	public void setFechaInicioProgramada(Date fechaInicioProgramada) {
		this.fechaInicioProgramada = fechaInicioProgramada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaFinReal", length = 23)
	public Date getFechaFinReal() {
		return this.fechaFinReal;
	}

	public void setFechaFinReal(Date fechaFinReal) {
		this.fechaFinReal = fechaFinReal;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@Column(name = "tipoTarea")
	public Integer getTipoTarea() {
		return this.tipoTarea;
	}

	public void setTipoTarea(Integer tipoTarea) {
		this.tipoTarea = tipoTarea;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "horaInicioProgramada")
	public Integer getHoraInicioProgramada() {
		return this.horaInicioProgramada;
	}

	public void setHoraInicioProgramada(Integer horaInicioProgramada) {
		this.horaInicioProgramada = horaInicioProgramada;
	}

	@Column(name = "horaFinReal")
	public Integer getHoraFinReal() {
		return this.horaFinReal;
	}

	public void setHoraFinReal(Integer horaFinReal) {
		this.horaFinReal = horaFinReal;
	}

	@Column(name = "horaInicioReal")
	public Integer getHoraInicioReal() {
		return this.horaInicioReal;
	}

	public void setHoraInicioReal(Integer horaInicioReal) {
		this.horaInicioReal = horaInicioReal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaInicioReal", length = 23)
	public Date getFechaInicioReal() {
		return this.fechaInicioReal;
	}

	public void setFechaInicioReal(Date fechaInicioReal) {
		this.fechaInicioReal = fechaInicioReal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaFinProgramada", length = 23)
	public Date getFechaFinProgramada() {
		return this.fechaFinProgramada;
	}

	public void setFechaFinProgramada(Date fechaFinProgramada) {
		this.fechaFinProgramada = fechaFinProgramada;
	}

	@Column(name = "horaFinProgramada")
	public Integer getHoraFinProgramada() {
		return this.horaFinProgramada;
	}

	public void setHoraFinProgramada(Integer horaFinProgramada) {
		this.horaFinProgramada = horaFinProgramada;
	}

	@Column(name = "recordarAntes")
	public Integer getRecordarAntes() {
		return this.recordarAntes;
	}

	public void setRecordarAntes(Integer recordarAntes) {
		this.recordarAntes = recordarAntes;
	}

}
