package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TecnicoGrupoId generated by hbm2java
 */
@Embeddable
public class TecnicoGrupoId implements java.io.Serializable {

	private int codigoGrupo;
	private int codigoUsuario;

	public TecnicoGrupoId() {
	}

	public TecnicoGrupoId(int codigoGrupo, int codigoUsuario) {
		this.codigoGrupo = codigoGrupo;
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigoGrupo", nullable = false)
	public int getCodigoGrupo() {
		return this.codigoGrupo;
	}

	public void setCodigoGrupo(int codigoGrupo) {
		this.codigoGrupo = codigoGrupo;
	}

	@Column(name = "codigoUsuario", nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TecnicoGrupoId))
			return false;
		TecnicoGrupoId castOther = (TecnicoGrupoId) other;

		return (this.getCodigoGrupo() == castOther.getCodigoGrupo())
				&& (this.getCodigoUsuario() == castOther.getCodigoUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoGrupo();
		result = 37 * result + this.getCodigoUsuario();
		return result;
	}

}
