package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Tecnico generated by hbm2java
 */
@Entity
@Table(name = "TECNICO", schema = "dbo", catalog = "SISMAV2")
public class Tecnico implements java.io.Serializable {

	private int codigoUsuario;
	private Usuario usuario;
	private String idCorreoSms;
	private BigDecimal tarifa;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;
	private Set<ProblemaResponsable> problemaResponsables = new HashSet<ProblemaResponsable>(
			0);
	private Set<TecnicoSitio> tecnicoSitios = new HashSet<TecnicoSitio>(0);
	private Set<CambioResponsable> cambioResponsables = new HashSet<CambioResponsable>(
			0);
	private Set<SolicitudResponsable> solicitudResponsables = new HashSet<SolicitudResponsable>(
			0);
	private Set<EntradaTiempo> entradaTiempos = new HashSet<EntradaTiempo>(0);
	private Set<TecnicoGrupo> tecnicoGrupos = new HashSet<TecnicoGrupo>(0);
	private Set<Tarea> tareas = new HashSet<Tarea>(0);
	private Set<ProblemaEntTiempo> problemaEntTiempos = new HashSet<ProblemaEntTiempo>(
			0);

	public Tecnico() {
	}

	public Tecnico(Usuario usuario) {
		this.usuario = usuario;
	}

	public Tecnico(Usuario usuario, String idCorreoSms, BigDecimal tarifa,
			Integer estado, String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion,
			Set<ProblemaResponsable> problemaResponsables,
			Set<TecnicoSitio> tecnicoSitios,
			Set<CambioResponsable> cambioResponsables,
			Set<SolicitudResponsable> solicitudResponsables,
			Set<EntradaTiempo> entradaTiempos, Set<TecnicoGrupo> tecnicoGrupos,
			Set<Tarea> tareas, Set<ProblemaEntTiempo> problemaEntTiempos) {
		this.usuario = usuario;
		this.idCorreoSms = idCorreoSms;
		this.tarifa = tarifa;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
		this.problemaResponsables = problemaResponsables;
		this.tecnicoSitios = tecnicoSitios;
		this.cambioResponsables = cambioResponsables;
		this.solicitudResponsables = solicitudResponsables;
		this.entradaTiempos = entradaTiempos;
		this.tecnicoGrupos = tecnicoGrupos;
		this.tareas = tareas;
		this.problemaEntTiempos = problemaEntTiempos;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "usuario"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "codigoUsuario", unique = true, nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "idCorreoSms", length = 50)
	public String getIdCorreoSms() {
		return this.idCorreoSms;
	}

	public void setIdCorreoSms(String idCorreoSms) {
		this.idCorreoSms = idCorreoSms;
	}

	@Column(name = "tarifa", precision = 10)
	public BigDecimal getTarifa() {
		return this.tarifa;
	}

	public void setTarifa(BigDecimal tarifa) {
		this.tarifa = tarifa;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tecnico")
	public Set<ProblemaResponsable> getProblemaResponsables() {
		return this.problemaResponsables;
	}

	public void setProblemaResponsables(
			Set<ProblemaResponsable> problemaResponsables) {
		this.problemaResponsables = problemaResponsables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tecnico")
	public Set<TecnicoSitio> getTecnicoSitios() {
		return this.tecnicoSitios;
	}

	public void setTecnicoSitios(Set<TecnicoSitio> tecnicoSitios) {
		this.tecnicoSitios = tecnicoSitios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tecnico")
	public Set<CambioResponsable> getCambioResponsables() {
		return this.cambioResponsables;
	}

	public void setCambioResponsables(Set<CambioResponsable> cambioResponsables) {
		this.cambioResponsables = cambioResponsables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tecnico")
	public Set<SolicitudResponsable> getSolicitudResponsables() {
		return this.solicitudResponsables;
	}

	public void setSolicitudResponsables(
			Set<SolicitudResponsable> solicitudResponsables) {
		this.solicitudResponsables = solicitudResponsables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tecnico")
	public Set<EntradaTiempo> getEntradaTiempos() {
		return this.entradaTiempos;
	}

	public void setEntradaTiempos(Set<EntradaTiempo> entradaTiempos) {
		this.entradaTiempos = entradaTiempos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tecnico")
	public Set<TecnicoGrupo> getTecnicoGrupos() {
		return this.tecnicoGrupos;
	}

	public void setTecnicoGrupos(Set<TecnicoGrupo> tecnicoGrupos) {
		this.tecnicoGrupos = tecnicoGrupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tecnico")
	public Set<Tarea> getTareas() {
		return this.tareas;
	}

	public void setTareas(Set<Tarea> tareas) {
		this.tareas = tareas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tecnico")
	public Set<ProblemaEntTiempo> getProblemaEntTiempos() {
		return this.problemaEntTiempos;
	}

	public void setProblemaEntTiempos(Set<ProblemaEntTiempo> problemaEntTiempos) {
		this.problemaEntTiempos = problemaEntTiempos;
	}

}
