package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoArrendamiento generated by hbm2java
 */
@Entity
@Table(name = "TIPO_ARRENDAMIENTO", schema = "dbo", catalog = "SISMAV2")
public class TipoArrendamiento implements java.io.Serializable {

	private int codigoTipoArrendamiento;
	private String nombreTipoArrendamiento;
	private String descripcion;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;

	public TipoArrendamiento() {
	}

	public TipoArrendamiento(int codigoTipoArrendamiento) {
		this.codigoTipoArrendamiento = codigoTipoArrendamiento;
	}

	public TipoArrendamiento(int codigoTipoArrendamiento,
			String nombreTipoArrendamiento, String descripcion, Integer estado,
			String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion) {
		this.codigoTipoArrendamiento = codigoTipoArrendamiento;
		this.nombreTipoArrendamiento = nombreTipoArrendamiento;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
	}

	@Id
	@Column(name = "codigoTipoArrendamiento", unique = true, nullable = false)
	public int getCodigoTipoArrendamiento() {
		return this.codigoTipoArrendamiento;
	}

	public void setCodigoTipoArrendamiento(int codigoTipoArrendamiento) {
		this.codigoTipoArrendamiento = codigoTipoArrendamiento;
	}

	@Column(name = "nombreTipoArrendamiento", length = 50)
	public String getNombreTipoArrendamiento() {
		return this.nombreTipoArrendamiento;
	}

	public void setNombreTipoArrendamiento(String nombreTipoArrendamiento) {
		this.nombreTipoArrendamiento = nombreTipoArrendamiento;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

}
