package com.alfa.consulting.persistencia.entidades;

// Generated 07/05/2012 01:03:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO", schema = "dbo", catalog = "SISMAV2")
public class Usuario implements java.io.Serializable {

	private int codigoUsuario;
	private Organizacion organizacion;
	private String primerNombre;
	private String segundoNombre;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private Integer tipoDocumento;
	private String nroDocumento;
	private Date fechaNacimiento;
	private Integer sexo;
	private String telefono;
	private String movil;
	private String direccion;
	private Integer tipoUsuario;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String terminalCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String terminalModificacion;
	private String nombreUsuario;
	private String idEmpleado;
	private Boolean habilitarSesion;
	private Boolean solicitudServicio;
	private Boolean ordenCompra;
	private String nombreCargo;
	private String email;
	private String imagen;
	private Cliente cliente;
	private Set<Vista> vistas = new HashSet<Vista>(0);
	private Tecnico tecnico;
	private Set<Favorito> favoritos = new HashSet<Favorito>(0);
	private Set<Login> logins = new HashSet<Login>(0);
	private Set<SolicitudAprobacion> solicitudAprobacions = new HashSet<SolicitudAprobacion>(
			0);
	private Set<MiembroCab> miembroCabs = new HashSet<MiembroCab>(0);
	private Set<UsuarioFuncion> usuarioFuncions = new HashSet<UsuarioFuncion>(0);
	private Set<ElementoReciente> elementoRecientes = new HashSet<ElementoReciente>(
			0);

	public Usuario() {
	}

	public Usuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public Usuario(int codigoUsuario, Organizacion organizacion,
			String primerNombre, String segundoNombre, String apellidoPaterno,
			String apellidoMaterno, Integer tipoDocumento, String nroDocumento,
			Date fechaNacimiento, Integer sexo, String telefono, String movil,
			String direccion, Integer tipoUsuario, Integer estado,
			String usuarioCreacion, Date fechaCreacion,
			String terminalCreacion, String usuarioModificacion,
			Date fechaModificacion, String terminalModificacion,
			String nombreUsuario, String idEmpleado, Boolean habilitarSesion,
			Boolean solicitudServicio, Boolean ordenCompra, String nombreCargo,
			String email, String imagen, Cliente cliente, Set<Vista> vistas,
			Tecnico tecnico, Set<Favorito> favoritos, Set<Login> logins,
			Set<SolicitudAprobacion> solicitudAprobacions,
			Set<MiembroCab> miembroCabs, Set<UsuarioFuncion> usuarioFuncions,
			Set<ElementoReciente> elementoRecientes) {
		this.codigoUsuario = codigoUsuario;
		this.organizacion = organizacion;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.tipoDocumento = tipoDocumento;
		this.nroDocumento = nroDocumento;
		this.fechaNacimiento = fechaNacimiento;
		this.sexo = sexo;
		this.telefono = telefono;
		this.movil = movil;
		this.direccion = direccion;
		this.tipoUsuario = tipoUsuario;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.terminalCreacion = terminalCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.terminalModificacion = terminalModificacion;
		this.nombreUsuario = nombreUsuario;
		this.idEmpleado = idEmpleado;
		this.habilitarSesion = habilitarSesion;
		this.solicitudServicio = solicitudServicio;
		this.ordenCompra = ordenCompra;
		this.nombreCargo = nombreCargo;
		this.email = email;
		this.imagen = imagen;
		this.cliente = cliente;
		this.vistas = vistas;
		this.tecnico = tecnico;
		this.favoritos = favoritos;
		this.logins = logins;
		this.solicitudAprobacions = solicitudAprobacions;
		this.miembroCabs = miembroCabs;
		this.usuarioFuncions = usuarioFuncions;
		this.elementoRecientes = elementoRecientes;
	}

	@Id
	@Column(name = "codigoUsuario", unique = true, nullable = false)
	public int getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(int codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigoOrganizacion")
	public Organizacion getOrganizacion() {
		return this.organizacion;
	}

	public void setOrganizacion(Organizacion organizacion) {
		this.organizacion = organizacion;
	}

	@Column(name = "primerNombre", length = 50)
	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	@Column(name = "segundoNombre", length = 50)
	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	@Column(name = "apellidoPaterno", length = 50)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "apellidoMaterno", length = 50)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "tipoDocumento")
	public Integer getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(Integer tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "nroDocumento", length = 20)
	public String getNroDocumento() {
		return this.nroDocumento;
	}

	public void setNroDocumento(String nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaNacimiento", length = 23)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "sexo")
	public Integer getSexo() {
		return this.sexo;
	}

	public void setSexo(Integer sexo) {
		this.sexo = sexo;
	}

	@Column(name = "telefono", length = 30)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "movil", length = 30)
	public String getMovil() {
		return this.movil;
	}

	public void setMovil(String movil) {
		this.movil = movil;
	}

	@Column(name = "direccion", length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "tipoUsuario")
	public Integer getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(Integer tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "usuarioCreacion", length = 50)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "terminalCreacion", length = 50)
	public String getTerminalCreacion() {
		return this.terminalCreacion;
	}

	public void setTerminalCreacion(String terminalCreacion) {
		this.terminalCreacion = terminalCreacion;
	}

	@Column(name = "usuarioModificacion", length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "terminalModificacion", length = 50)
	public String getTerminalModificacion() {
		return this.terminalModificacion;
	}

	public void setTerminalModificacion(String terminalModificacion) {
		this.terminalModificacion = terminalModificacion;
	}

	@Column(name = "nombreUsuario", length = 50)
	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	@Column(name = "idEmpleado", length = 50)
	public String getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(String idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	@Column(name = "habilitarSesion")
	public Boolean getHabilitarSesion() {
		return this.habilitarSesion;
	}

	public void setHabilitarSesion(Boolean habilitarSesion) {
		this.habilitarSesion = habilitarSesion;
	}

	@Column(name = "solicitudServicio")
	public Boolean getSolicitudServicio() {
		return this.solicitudServicio;
	}

	public void setSolicitudServicio(Boolean solicitudServicio) {
		this.solicitudServicio = solicitudServicio;
	}

	@Column(name = "ordenCompra")
	public Boolean getOrdenCompra() {
		return this.ordenCompra;
	}

	public void setOrdenCompra(Boolean ordenCompra) {
		this.ordenCompra = ordenCompra;
	}

	@Column(name = "nombreCargo", length = 50)
	public String getNombreCargo() {
		return this.nombreCargo;
	}

	public void setNombreCargo(String nombreCargo) {
		this.nombreCargo = nombreCargo;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "imagen", length = 1000)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Vista> getVistas() {
		return this.vistas;
	}

	public void setVistas(Set<Vista> vistas) {
		this.vistas = vistas;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Tecnico getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Favorito> getFavoritos() {
		return this.favoritos;
	}

	public void setFavoritos(Set<Favorito> favoritos) {
		this.favoritos = favoritos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Login> getLogins() {
		return this.logins;
	}

	public void setLogins(Set<Login> logins) {
		this.logins = logins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<SolicitudAprobacion> getSolicitudAprobacions() {
		return this.solicitudAprobacions;
	}

	public void setSolicitudAprobacions(
			Set<SolicitudAprobacion> solicitudAprobacions) {
		this.solicitudAprobacions = solicitudAprobacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<MiembroCab> getMiembroCabs() {
		return this.miembroCabs;
	}

	public void setMiembroCabs(Set<MiembroCab> miembroCabs) {
		this.miembroCabs = miembroCabs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioFuncion> getUsuarioFuncions() {
		return this.usuarioFuncions;
	}

	public void setUsuarioFuncions(Set<UsuarioFuncion> usuarioFuncions) {
		this.usuarioFuncions = usuarioFuncions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<ElementoReciente> getElementoRecientes() {
		return this.elementoRecientes;
	}

	public void setElementoRecientes(Set<ElementoReciente> elementoRecientes) {
		this.elementoRecientes = elementoRecientes;
	}

}
